import { QuestionBank } from "./types";

export const questionBank: QuestionBank = {
  friends: {
    "would-you-rather": {
      low: [
        "Would you rather be able to fly or be invisible?",
        "Would you rather always have to sing instead of speak, or dance everywhere you walk?",
        "Would you rather live in a treehouse or a houseboat?",
        "Would you rather have a pet dragon or a pet unicorn?",
        "Would you rather only eat pizza or only eat tacos for a year?",
        "Would you rather have super speed or super strength?",
        "Would you rather explore space or explore the deep ocean?",
        "Would you rather always have to whisper or always have to shout?",
        "Would you rather live without music or live without movies?",
        "Would you rather have a rewind button or a pause button for your life?",
        "Would you rather be a famous chef or a famous musician?",
        "Would you rather never use social media again or never watch TV again?",
        "Would you rather talk to animals or speak every human language?",
        "Would you rather go camping in the mountains or relax on a beach?",
        "Would you rather always win at board games or always win at video games?",
        "Would you rather have unlimited tacos or unlimited ice cream for life?",
        "Would you rather teleport anywhere or freeze time whenever you want?",
      ],
      medium: [
        "Would you rather accidentally send a text about someone to that person, or call your teacher mom or dad in front of the class again?",
        "Would you rather be famous for something embarrassing or never be famous at all?",
        "Would you rather always say what's on your mind or never share an opinion again?",
        "Would you rather find out your best friend talks about you behind your back (nicely) or never know what people say about you?",
        "Would you rather date someone your friends hate but you love, or date someone your friends love but you're just meh about?",
        "Would you rather be stuck in an elevator with your crush or with your worst enemy?",
        "Would you rather have everyone know your search history or your text messages?",
        "Would you rather give an embarrassing toast at a wedding or trip on stage in front of a crowd?",
        "Would you rather lose all your money or lose all your friends?",
        "Would you rather tell everyone the truth about what you think of them, or never speak to anyone again?",
        "Would you rather your parents read your diary or your browser history?",
        "Would you rather be roasted by everyone in this room or have to roast everyone yourself?",
        "Would you rather admit your biggest fear out loud or share your most embarrassing childhood memory?",
        "Would you rather have a group chat exposed to your family or your boss?",
        "Would you rather find out who has a crush on you, or find out who talks trash about you?",
        "Would you rather be forced to tell a secret every hour or never keep a secret again?",
        "Would you rather kiss and tell everything, or never talk about your love life again?",
      ],
      high: [
        "Would you rather kiss the person to your left or arm wrestle the person to your right for a prize?",
        "Would you rather share your last five DMs with the group, or let someone post on your social media unsupervised for a day?",
        "Would you rather have everyone read your last five texts out loud, or sing your last search out loud?",
        "Would you rather admit who in this room you'd date, or who you'd never date?",
        "Would you rather reveal your worst dating app opener, or confess your worst date story?",
        "Would you rather let the group rate your dating profile live, or let them pick your next bio?",
        "Would you rather tell the group your biggest turn-off, or your biggest ick?",
        "Would you rather share the last lie you told a friend, or the last lie a friend told you that you know of?",
        "Would you rather admit your pettiest reason for ending a friendship, or a relationship?",
        "Would you rather let the group scroll your camera roll for ten seconds, or your recent calls list?",
        "Would you rather confess a crush you've never told anyone about, or reveal who you stalked most on social media this year?",
        "Would you rather do a dare chosen by the group right now, or answer any one question with total honesty?",
        "Would you rather admit the most embarrassing thing you've done for attention, or the pettiest thing you've done out of jealousy?",
        "Would you rather tell everyone your red flag, or let them guess it?",
        "Would you rather reveal the last time you cried and why, or the last time you lied about being fine?",
        "Would you rather let the room ask you anything for the next sixty seconds, or complete a dare of their choice?",
        "Would you rather admit who you'd pick in a kiss-marry-avoid with two people in this room, or sit out this round?",
      ],
    },
    "two-truths-a-lie": {
      low: [
        "Share three statements about your childhood pets, hobbies, or favorite foods — two true, one false.",
        "Share three statements about a trip you've taken — two true, one false.",
        "Share three statements about your family — two true, one false.",
        "Share three statements about your first job — two true, one false.",
        "Share three statements about your favorite school subject — two true, one false.",
        "Share three statements about a talent or skill you have — two true, one false.",
        "Share three statements about your bedroom growing up — two true, one false.",
        "Share three statements about your favorite movie or show — two true, one false.",
        "Share three statements about your best childhood friend — two true, one false.",
        "Share three statements about a sport or hobby you tried — two true, one false.",
        "Share three statements about something you collect or used to collect — two true, one false.",
        "Share three statements about your dream vacation — two true, one false.",
        "Share three statements about your favorite holiday tradition — two true, one false.",
        "Share three statements about the weirdest food you've eaten — two true, one false.",
        "Share three statements about your morning routine — two true, one false.",
        "Share three statements about a nickname you've had — two true, one false.",
        "Share three statements about your first concert or live event — two true, one false.",
      ],
      medium: [
        "Share three statements about your dating history — two true, one false.",
        "Share three statements about your worst date ever — two true, one false.",
        "Share three statements about a rule you've broken — two true, one false.",
        "Share three statements about an embarrassing moment in public — two true, one false.",
        "Share three statements about a lie you've told your parents — two true, one false.",
        "Share three statements about your biggest fear — two true, one false.",
        "Share three statements about a time you got in trouble — two true, one false.",
        "Share three statements about your celebrity crush history — two true, one false.",
        "Share three statements about a time you ghosted someone or got ghosted — two true, one false.",
        "Share three statements about your most impulsive purchase — two true, one false.",
        "Share three statements about a secret talent nobody knows about — two true, one false.",
        "Share three statements about your weirdest habit — two true, one false.",
        "Share three statements about a time you pretended to be sick — two true, one false.",
        "Share three statements about your most embarrassing autocorrect or typo — two true, one false.",
        "Share three statements about a crush you had that no one knew about — two true, one false.",
        "Share three statements about the last argument you had with a friend — two true, one false.",
        "Share three statements about something you regret saying — two true, one false.",
      ],
      high: [
        "Share three statements about your most embarrassing hookup story — two true, one false.",
        "Share three statements about a secret you've kept from your closest friend — two true, one false.",
        "Share three statements about your biggest relationship red flag — two true, one false.",
        "Share three statements about the wildest thing you've done at a party — two true, one false.",
        "Share three statements about someone you regret dating — two true, one false.",
        "Share three statements about a time you were caught doing something you shouldn't have — two true, one false.",
        "Share three statements about your most controversial opinion — two true, one false.",
        "Share three statements about a time you lied to get out of trouble — two true, one false.",
        "Share three statements about your most jealous moment in a relationship or friendship — two true, one false.",
        "Share three statements about a risky thing you've done for love or attention — two true, one false.",
        "Share three statements about the last time you cried in public — two true, one false.",
        "Share three statements about a time you broke someone's trust — two true, one false.",
        "Share three statements about your most embarrassing search history moment — two true, one false.",
        "Share three statements about a rumor that was started about you — two true, one false.",
        "Share three statements about the last person you had a crush on in this friend group — two true, one false.",
        "Share three statements about the riskiest thing you've done on a dare — two true, one false.",
        "Share three statements about a time you snooped through someone's phone — two true, one false.",
      ],
    },
    "never-have-i-ever": {
      low: [
        "Never have I ever gone skydiving.",
        "Never have I ever broken a bone.",
        "Never have I ever fallen asleep in class.",
        "Never have I ever sung karaoke in public.",
        "Never have I ever gotten lost in another city.",
        "Never have I ever pulled an all-nighter.",
        "Never have I ever cried during a movie.",
        "Never have I ever gone a full day without my phone.",
        "Never have I ever eaten something off the floor.",
        "Never have I ever forgotten someone's name right after meeting them.",
        "Never have I ever laughed so hard I cried.",
        "Never have I ever been on TV or in a newspaper.",
        "Never have I ever gone camping.",
        "Never have I ever won a trophy or award.",
        "Never have I ever tried to teach myself a new language and given up.",
        "Never have I ever fallen asleep during a movie in a theater.",
        "Never have I ever talked to myself out loud in public.",
      ],
      medium: [
        "Never have I ever pretended to like a gift I hated.",
        "Never have I ever stalked someone's social media for hours.",
        "Never have I ever lied about my age.",
        "Never have I ever ghosted someone.",
        "Never have I ever texted an ex I shouldn't have.",
        "Never have I ever pretended to be busy to avoid plans.",
        "Never have I ever taken credit for someone else's idea.",
        "Never have I ever cried to get out of trouble.",
        "Never have I ever had a crush on a friend's partner.",
        "Never have I ever lied on a resume or job application.",
        "Never have I ever snooped through a friend's phone.",
        "Never have I ever pretended to know a song I'd never heard.",
        "Never have I ever faked an excuse to leave a date early.",
        "Never have I ever talked about someone right after they left the room.",
        "Never have I ever accidentally liked an old photo while stalking someone's profile.",
        "Never have I ever lied about where I was.",
        "Never have I ever had a secret nickname for someone I didn't like.",
      ],
      high: [
        "Never have I ever had a crush on someone in this room.",
        "Never have I ever sent a risky text to the wrong person.",
        "Never have I ever kissed someone and regretted it.",
        "Never have I ever lied to a partner about where I was.",
        "Never have I ever had a one-night stand.",
        "Never have I ever been caught checking someone out.",
        "Never have I ever dated two people at the same time.",
        "Never have I ever snuck someone into my room.",
        "Never have I ever been in love with two people at once.",
        "Never have I ever hooked up with someone I met that same day.",
        "Never have I ever lied about my relationship status.",
        "Never have I ever had a secret relationship.",
        "Never have I ever flirted with someone to get something I wanted.",
        "Never have I ever been caught sneaking out.",
        "Never have I ever had feelings for someone's ex.",
        "Never have I ever sent a message I immediately wanted to unsend.",
        "Never have I ever kissed more than one person in the same week.",
      ],
    },
    "most-likely-to": {
      low: [
        "Who is most likely to become famous one day?",
        "Who is most likely to forget their own birthday?",
        "Who is most likely to win a reality TV show?",
        "Who is most likely to become a millionaire?",
        "Who is most likely to survive a zombie apocalypse?",
        "Who is most likely to become a professional athlete?",
        "Who is most likely to move to another country?",
        "Who is most likely to write a book?",
        "Who is most likely to become a chef?",
        "Who is most likely to get lost using GPS?",
        "Who is most likely to adopt ten pets?",
        "Who is most likely to become the group's parent friend?",
        "Who is most likely to fall asleep first at a sleepover?",
        "Who is most likely to become an influencer?",
        "Who is most likely to cry during an animated movie?",
        "Who is most likely to start a business?",
        "Who is most likely to still be friends with everyone here in twenty years?",
      ],
      medium: [
        "Who is most likely to text an ex at 2am?",
        "Who is most likely to get married first?",
        "Who is most likely to forget a friend's birthday?",
        "Who is most likely to snoop through someone's phone?",
        "Who is most likely to cry over a breakup for months?",
        "Who is most likely to fall in love at first sight?",
        "Who is most likely to ghost someone?",
        "Who is most likely to stalk an ex on social media?",
        "Who is most likely to get in trouble at a party?",
        "Who is most likely to lie about being okay?",
        "Who is most likely to start drama without meaning to?",
        "Who is most likely to date someone the group doesn't approve of?",
        "Who is most likely to get a tattoo they regret?",
        "Who is most likely to fall for a bad joke every time?",
        "Who is most likely to accidentally double text their crush?",
        "Who is most likely to break a rule and not get caught?",
        "Who is most likely to overshare on a first date?",
      ],
      high: [
        "Who is most likely to have a secret admirer in this room?",
        "Who is most likely to get married and divorced within a year, on a dare?",
        "Who is most likely to flirt their way out of a speeding ticket?",
        "Who is most likely to have the wildest dating app stories?",
        "Who is most likely to have kissed someone in this room?",
        "Who is most likely to have a secret crush right now?",
        "Who is most likely to end up in a messy love triangle?",
        "Who is most likely to send a risky text and regret it instantly?",
        "Who is most likely to hook up with a stranger on vacation?",
        "Who is most likely to fall for their best friend?",
        "Who is most likely to have the most exes in this room?",
        "Who is most likely to be someone's rebound?",
        "Who is most likely to cause a scene at a wedding over an old flame?",
        "Who is most likely to have a secret relationship nobody knows about?",
        "Who is most likely to flirt with everyone at a party?",
        "Who is most likely to fall in love the fastest?",
        "Who is most likely to have a type that always gets them in trouble?",
      ],
    },
    "rapid-fire": {
      low: [
        "Name 3 breakfast foods before time runs out.",
        "Name 3 movies you could watch on repeat.",
        "Name 3 superheroes as fast as you can.",
        "Name 3 things you'd bring to a deserted island.",
        "Name 3 cartoon characters from your childhood.",
        "Name 3 songs stuck in your head lately.",
        "Name 3 countries you'd love to visit.",
        "Name 3 board games you actually enjoy.",
        "Name 3 smells that instantly make you happy.",
        "Name 3 things that are overrated.",
        "Name 3 snacks you could never give up.",
        "Name 3 apps on your phone you use daily.",
        "Name 3 things you'd buy if money was no object.",
        "Name 3 words that describe you in one breath.",
        "Name 3 places you consider home.",
        "Name 3 skills you wish you had.",
        "Name 3 things that instantly make your day better.",
      ],
      medium: [
        "Name 3 red flags in a relationship, fast.",
        "Name 3 things you'd never tell your parents.",
        "Name 3 celebrity crushes, no hesitating.",
        "Name 3 things you'd change about your life right now.",
        "Name 3 people you'd want on your side in an argument.",
        "Name 3 lies people tell on first dates.",
        "Name 3 things that instantly turn you off.",
        "Name 3 guilty pleasures you won't apologize for.",
        "Name 3 things you'd do if no one was watching.",
        "Name 3 traits your ideal partner needs.",
        "Name 3 things you're insecure about, quickly.",
        "Name 3 arguments you've had that were actually silly.",
        "Name 3 things you'd say in a toast that's a little too honest.",
        "Name 3 secrets you could tell right now, safe ones only.",
        "Name 3 people you'd want to swap lives with for a day.",
        "Name 3 things you do that annoy your friends.",
        "Name 3 excuses you've used to cancel plans.",
      ],
      high: [
        "Name 3 things you find instantly attractive, fast.",
        "Name 3 people in this room you'd trust with a secret.",
        "Name 3 dares you'd actually do right now.",
        "Name 3 things you'd never do, even on a dare.",
        "Name 3 red flags you've ignored in the past.",
        "Name 3 things you'd want to know about everyone's love life.",
        "Name 3 celebrities you'd want to switch lives with for a wild weekend.",
        "Name 3 secrets you'll take to the grave, or almost.",
        "Name 3 things that make you a good, or bad, partner.",
        "Name 3 things you'd do differently in your last relationship.",
        "Name 3 people you'd pick for a kiss-marry-avoid without hesitating.",
        "Name 3 things you'd confess after one drink.",
        "Name 3 things about your dating life you've never told this group.",
        "Name 3 rules you'd break for the right person.",
        "Name 3 things you find irresistible in someone.",
        "Name 3 moments you'd redo if you could.",
        "Name 3 things you'd want a partner to never find out.",
      ],
    },
    charades: {
      low: [
        "Act out: Brushing your teeth.",
        "Act out: Riding a rollercoaster.",
        "Act out: Building a sandcastle.",
        "Act out: Walking a dog.",
        "Act out: Making a sandwich.",
        "Act out: Playing the guitar.",
        "Act out: Ice skating.",
        "Act out: Flying a kite.",
        "Act out: Taking a selfie.",
        "Act out: Cooking a fancy dinner.",
        "Act out: Doing yoga.",
        "Act out: Fishing.",
        "Act out: Painting a wall.",
        "Act out: Blowing up a balloon.",
        "Act out: Riding a horse.",
        "Act out: Playing basketball.",
        "Act out: Folding laundry.",
      ],
      medium: [
        "Act out: Getting caught in a lie.",
        "Act out: A bad first date.",
        "Act out: Winning the lottery.",
        "Act out: Being scared of a spider.",
        "Act out: Sneaking out of the house.",
        "Act out: A breakup phone call.",
        "Act out: Trying not to laugh at a funeral.",
        "Act out: Getting a text from your crush.",
        "Act out: Being stuck in traffic and late.",
        "Act out: An awkward elevator ride.",
        "Act out: A job interview gone wrong.",
        "Act out: Meeting your partner's parents for the first time.",
        "Act out: Losing a game and being a sore loser.",
        "Act out: Being caught snooping.",
        "Act out: A first kiss that goes badly.",
        "Act out: Realizing you texted the wrong person.",
        "Act out: A dramatic soap opera argument.",
      ],
      high: [
        "Act out: Flirting badly at a bar.",
        "Act out: A seductive walk across the room.",
        "Act out: A steamy soap opera reunion scene.",
        "Act out: Being caught mid-daydream about your crush.",
        "Act out: A dramatic love confession.",
        "Act out: Slow dancing with an imaginary partner.",
        "Act out: A jealous partner catching their date flirting.",
        "Act out: Sending a risky text and immediately regretting it.",
        "Act out: A first date that turns into a spark.",
        "Act out: Being swept off your feet.",
        "Act out: A dramatic breakup in a movie.",
        "Act out: Winking at someone across the room.",
        "Act out: A romantic proposal gone wrong.",
        "Act out: Getting caught staring at your crush.",
        "Act out: A passionate reunion at an airport.",
        "Act out: Trying to play it cool after a compliment.",
        "Act out: A love triangle confrontation.",
      ],
    },
  },
  couples: {
    "would-you-rather": {
      low: [
        "Would you rather cook together every night or order takeout together every night?",
        "Would you rather travel somewhere new together every year or perfect one favorite destination?",
        "Would you rather slow dance in the kitchen or stargaze on a rooftop?",
        "Would you rather get matching pajamas or matching mugs?",
        "Would you rather have a lazy Sunday movie marathon or an adventurous day trip?",
        "Would you rather always get the window seat or always pick the playlist on road trips?",
        "Would you rather redecorate a room together or plan a trip together?",
        "Would you rather adopt a dog or a cat together?",
        "Would you rather have breakfast in bed every weekend or dessert after every dinner?",
        "Would you rather learn a new hobby together or perfect one you already share?",
        "Would you rather send each other good morning texts or good night texts every day?",
        "Would you rather have a home-cooked date night in or a dressed-up date night out?",
        "Would you rather plan surprises for each other or always know what's coming?",
        "Would you rather share a playlist or share a watchlist?",
        "Would you rather take a cooking class together or a dance class together?",
        "Would you rather have a couple's nickname or a couple's handshake?",
        "Would you rather spend a rainy day baking together or reading together?",
      ],
      medium: [
        "Would you rather know exactly what I'm thinking, or have me always tell you the truth even when it's hard?",
        "Would you rather I plan every date, or we take turns surprising each other?",
        "Would you rather we argue it out immediately, or take space and talk later?",
        "Would you rather I be brutally honest about your cooking, or always say it's great?",
        "Would you rather relive our first date, or fast-forward to a future memory together?",
        "Would you rather I remember every anniversary perfectly, or surprise you randomly instead?",
        "Would you rather know my biggest fear about us, or my biggest hope for us?",
        "Would you rather we split chores strictly evenly, or trade off based on who minds less?",
        "Would you rather I tell you when you're wrong right away, or pick my battles?",
        "Would you rather do a relationship check-in for fun, or never feel the need to?",
        "Would you rather I show affection more in public, or more in private?",
        "Would you rather know what my friends really think of you, or never ask?",
        "Would you rather we make every big decision together, or trust each other to decide solo sometimes?",
        "Would you rather I apologize first even when I'm not wrong, or we both hold our ground until it's resolved?",
        "Would you rather know my exact love language, or guess it through trial and error forever?",
        "Would you rather we keep separate finances, or merge everything?",
        "Would you rather I tell you a hard truth now, or protect your feelings and wait?",
      ],
      high: [
        "Would you rather I whisper what I love about your body or what I love about your mind — pick one, right now?",
        "Would you rather a slow, romantic night in or a spontaneous, passionate night out?",
        "Would you rather I tell you my biggest fantasy about us, or you guess it first?",
        "Would you rather recreate our first kiss, or our best kiss so far?",
        "Would you rather I describe exactly what attracts me to you physically, or emotionally?",
        "Would you rather a whole night of just kissing, or a whole night of just talking in bed?",
        "Would you rather know what I think about right before I fall asleep next to you, or right when I wake up?",
        "Would you rather I plan a surprise seductive evening, or you plan one for me?",
        "Would you rather we try something new and a little daring together, or perfect something we already love?",
        "Would you rather I tell you the moment I knew I was attracted to you, or the moment I knew I loved you?",
        "Would you rather a slow dance with wandering hands, or a passionate kiss goodbye at the door?",
        "Would you rather I confess my most honest thought about you right now, out loud?",
        "Would you rather spend the next hour giving compliments, or giving massages?",
        "Would you rather I tell you what I find irresistible about you in the morning, or at night?",
        "Would you rather we skip the small talk tonight and go straight to pillow talk?",
        "Would you rather I show you, or tell you, how much I want you right now?",
        "Would you rather a candlelit bath together, or a blanket fort with wandering hands?",
      ],
    },
    "two-truths-a-lie": {
      low: [
        "Share three statements about how you pictured your future partner as a kid — two true, one false.",
        "Share three statements about your first celebrity crush — two true, one false.",
        "Share three statements about your idea of a perfect date — two true, one false.",
        "Share three statements about your favorite memory together — two true, one false.",
        "Share three statements about what you thought of your partner when you first met — two true, one false.",
        "Share three statements about your love language — two true, one false.",
        "Share three statements about a gift you've given or received — two true, one false.",
        "Share three statements about your dream home together — two true, one false.",
        "Share three statements about a trip you'd love to take together — two true, one false.",
        "Share three statements about your favorite lazy day activity together — two true, one false.",
        "Share three statements about your first impression of your partner's family — two true, one false.",
        "Share three statements about a tradition you'd like to start together — two true, one false.",
        "Share three statements about your wedding, past or future — two true, one false.",
        "Share three statements about a compliment you've received from your partner — two true, one false.",
        "Share three statements about your favorite date you've been on together — two true, one false.",
        "Share three statements about something you admire about your partner — two true, one false.",
        "Share three statements about how you'd describe your relationship to a stranger — two true, one false.",
      ],
      medium: [
        "Share three statements about your past relationships — two true, one false.",
        "Share three statements about a fight you've had and how it ended — two true, one false.",
        "Share three statements about a habit of your partner's you secretly love — two true, one false.",
        "Share three statements about a time you felt jealous — two true, one false.",
        "Share three statements about your biggest insecurity in relationships — two true, one false.",
        "Share three statements about the moment you knew this was serious — two true, one false.",
        "Share three statements about a time your partner surprised you — two true, one false.",
        "Share three statements about something you've never told your partner — two true, one false.",
        "Share three statements about a compromise you've had to make in this relationship — two true, one false.",
        "Share three statements about a time you almost broke up — two true, one false.",
        "Share three statements about your partner's family that surprised you — two true, one false.",
        "Share three statements about how you handle conflict — two true, one false.",
        "Share three statements about a white lie you've told your partner — two true, one false.",
        "Share three statements about your biggest relationship fear — two true, one false.",
        "Share three statements about a time you felt most loved — two true, one false.",
        "Share three statements about an ex that still comes up sometimes — two true, one false.",
        "Share three statements about something you'd change about how you two communicate — two true, one false.",
      ],
      high: [
        "Share three statements about your biggest fantasy involving your partner — two true, one false.",
        "Share three statements about the most attracted you've ever been to your partner — two true, one false.",
        "Share three statements about a risky or daring thing you've done together — two true, one false.",
        "Share three statements about your partner's most attractive quality — two true, one false.",
        "Share three statements about the first time you felt real chemistry with your partner — two true, one false.",
        "Share three statements about something you find irresistible about your partner — two true, one false.",
        "Share three statements about a place you'd love to be intimate together that you haven't tried — two true, one false.",
        "Share three statements about your wildest date idea — two true, one false.",
        "Share three statements about a moment you couldn't keep your hands off each other — two true, one false.",
        "Share three statements about something you've always wanted to try together — two true, one false.",
        "Share three statements about your partner's best physical feature, in your opinion — two true, one false.",
        "Share three statements about a daydream you've had about your partner — two true, one false.",
        "Share three statements about the most spontaneous thing you've done together — two true, one false.",
        "Share three statements about a compliment you've been too shy to say out loud — two true, one false.",
        "Share three statements about your idea of a perfect romantic night — two true, one false.",
        "Share three statements about something that instantly makes you attracted to your partner — two true, one false.",
        "Share three statements about a surprise you've kept secret to keep the romance alive — two true, one false.",
      ],
    },
    "never-have-i-ever": {
      low: [
        "Never have I ever forgotten our anniversary.",
        "Never have I ever cried during a romantic movie with you.",
        "Never have I ever fallen asleep during date night.",
        "Never have I ever planned a surprise date.",
        "Never have I ever stolen the blanket on purpose.",
        "Never have I ever written you a love note.",
        "Never have I ever taken a cute photo of you without you knowing.",
        "Never have I ever pretended to like a gift from you.",
        "Never have I ever sung to you on purpose.",
        "Never have I ever danced with you in the kitchen.",
        "Never have I ever saved a text from you because it made me smile.",
        "Never have I ever cooked you a meal that didn't go as planned.",
        "Never have I ever cried happy tears because of you.",
        "Never have I ever bragged about you to a stranger.",
        "Never have I ever kept a ticket stub or memento from a date.",
        "Never have I ever planned our whole future out loud in my head.",
        "Never have I ever gotten butterflies just from a text from you.",
      ],
      medium: [
        "Never have I ever gone through your phone.",
        "Never have I ever been jealous of one of your friends.",
        "Never have I ever exaggerated a story to look better in front of you.",
        "Never have I ever pretended to be asleep to avoid a conversation.",
        "Never have I ever compared our relationship to someone else's.",
        "Never have I ever gotten annoyed and not said why.",
        "Never have I ever kept score of who did more chores.",
        "Never have I ever vented about you to a friend when I was upset.",
        "Never have I ever Googled an ex of yours.",
        "Never have I ever pretended to be fine when I wasn't.",
        "Never have I ever felt insecure about something you said.",
        "Never have I ever gone to bed angry instead of talking it out.",
        "Never have I ever exaggerated how bad my day was for sympathy.",
        "Never have I ever checked your location without telling you.",
        "Never have I ever brought up an old argument during a new one.",
        "Never have I ever been embarrassed by something you did in public.",
        "Never have I ever wondered what our life would look like with someone else.",
      ],
      high: [
        "Never have I ever fantasized about you during the day.",
        "Never have I ever tried to seduce you and failed.",
        "Never have I ever gotten jealous seeing someone flirt with you.",
        "Never have I ever sent you a flirty text just to get a reaction.",
        "Never have I ever thought about our first kiss more than once in a day.",
        "Never have I ever wanted to skip an event just to stay in with you.",
        "Never have I ever gotten distracted mid-conversation because of how you looked.",
        "Never have I ever planned a whole evening just to set the mood.",
        "Never have I ever felt nervous before being intimate with you, even now.",
        "Never have I ever thought about a place I'd want to kiss you that we haven't tried.",
        "Never have I ever gotten competitive trying to make you laugh in bed.",
        "Never have I ever replayed a moment with you because it was that good.",
        "Never have I ever gotten shy telling you what I want.",
        "Never have I ever tried a new move just to see your reaction.",
        "Never have I ever wanted to leave a party early just to be alone with you.",
        "Never have I ever complimented you just to see you blush.",
        "Never have I ever thought you looked irresistible in something completely ordinary.",
      ],
    },
    "truth-or-dare": {
      low: [
        "Truth: What's the first thing you noticed about me?",
        "Dare: Give your partner a genuine compliment about something non-physical.",
        "Truth: What's your favorite memory of us so far?",
        "Dare: Recreate the way we first said hello.",
        "Truth: What song reminds you of me?",
        "Dare: Do your best impression of your partner for thirty seconds.",
        "Truth: What's one thing you'd love for us to do together this year?",
        "Dare: Give your partner a two-minute hand massage.",
        "Truth: What's your favorite nickname you've had for me?",
        "Dare: Write a one-line love note and read it out loud.",
        "Truth: What made you say yes to our first date?",
        "Dare: Slow dance together for one minute, even without music.",
        "Truth: What's a small thing I do that makes you smile?",
        "Dare: Take a silly selfie together right now.",
        "Truth: What's your favorite way I show I care?",
        "Dare: Whisper something sweet in your partner's ear.",
        "Truth: What's one thing about me you're proud to show off to others?",
      ],
      medium: [
        "Truth: What's something small that instantly puts you in a bad mood?",
        "Dare: Tell your partner the truth about the last time you were annoyed with them.",
        "Truth: What's a compromise you've made that you're still not totally okay with?",
        "Dare: Text a compliment to your partner right now, even though they're next to you.",
        "Truth: What's something you wish I understood better about you?",
        "Dare: Give your partner a genuine apology for something small, even if it's already resolved.",
        "Truth: What's the pettiest thing you've ever been mad at me for?",
        "Dare: Let your partner ask you anything for the next minute, no dodging.",
        "Truth: When was the last time you felt unappreciated?",
        "Dare: Admit one thing you've been avoiding telling your partner.",
        "Truth: What's a habit of mine you've learned to live with?",
        "Dare: Tell your partner your honest first impression of them.",
        "Truth: What's something you're insecure about in this relationship?",
        "Dare: Give your partner three genuine compliments in a row, no repeats.",
        "Truth: What's a fear you have about our future?",
        "Dare: Let your partner pick your outfit for tomorrow, no complaints.",
        "Truth: What's something you've changed about yourself since being with me?",
      ],
      high: [
        "Truth: What's the most attracted to me you've ever been?",
        "Dare: Kiss your partner somewhere you don't usually.",
        "Truth: What's a fantasy you've never told me about?",
        "Dare: Whisper the first flirty thought that comes to mind.",
        "Truth: What's the boldest thing you've thought about doing with me?",
        "Dare: Give your partner a slow, lingering hug for thirty seconds.",
        "Truth: What outfit of mine drives you crazy?",
        "Dare: Describe out loud what you find irresistible about your partner right now.",
        "Truth: What's something daring you'd want to try together?",
        "Dare: Give your partner a kiss that lasts longer than a normal one.",
        "Truth: When did you last daydream about me during the day?",
        "Dare: Trace your finger along your partner's arm and tell them what you're thinking.",
        "Truth: What's your favorite way to be touched?",
        "Dare: Tell your partner exactly what you want to do the moment this game ends.",
        "Truth: What's the most turned on you've been by something I said?",
        "Dare: Let your partner choose where your next kiss lands.",
        "Truth: What's one thing you've always wanted me to do but never asked for?",
      ],
    },
    "how-well-do-you-know-me": {
      low: [
        "What's my favorite comfort food?",
        "What's my go-to order at our favorite restaurant?",
        "What's my favorite season and why?",
        "What was my favorite subject in school?",
        "What's my dream job, if money didn't matter?",
        "What's my favorite way to relax after a long day?",
        "Who's my celebrity crush?",
        "What's my favorite movie of all time?",
        "What's a hobby I've always wanted to try?",
        "What's my biggest pet peeve?",
        "What's my go-to karaoke song?",
        "What's my favorite holiday?",
        "What was I like as a kid, in one word?",
        "What's my love language?",
        "What's my favorite way to spend a weekend?",
        "What's a place I've always wanted to travel to?",
        "What's my favorite thing about our relationship?",
      ],
      medium: [
        "What's my biggest fear?",
        "What's something I'm insecure about?",
        "What's a goal I haven't told many people about?",
        "What's my biggest pet peeve about you, specifically?",
        "What's something that stresses me out that I don't always show?",
        "Who's someone I look up to, and why?",
        "What's a fight we had that actually taught you something about me?",
        "What's something I need more of from you emotionally?",
        "What's a habit of mine I'm trying to break?",
        "What do you think is my biggest strength in this relationship?",
        "What's something I regret not doing?",
        "What's a topic I get defensive about?",
        "What do you think I'd change about our relationship if I could?",
        "What's something I've never admitted I'm jealous of?",
        "What's my honest first impression of your closest friend?",
        "What's something I need space for?",
        "What do you think is my love language, and do I show it the way I want to receive it?",
      ],
      high: [
        "What's my biggest turn-on?",
        "What's the moment you think I was most attracted to you?",
        "What do you think is my biggest fantasy?",
        "What's something you think I find irresistible about you?",
        "What's my favorite way to be complimented in an intimate moment?",
        "What do you think crosses my mind when I look at you across a room?",
        "What's something bold you think I'd want to try with you?",
        "What do you think is the most attractive thing about you, according to me?",
        "What's a place you think I'd want to be alone with you?",
        "What do you think I find hardest to say out loud in the bedroom?",
        "What's the boldest compliment you think I've been holding back?",
        "What do you think is my favorite memory of us being intimate?",
        "What's something you think I daydream about doing with you?",
        "What outfit do you think drives me the craziest?",
        "What's something you think I've never told you I want?",
        "What do you think I find most attractive about how you show affection?",
        "What's a moment you think changed how attracted I am to you?",
      ],
    },
    "intimate-questions": {
      low: [
        "What made you fall for me, even a little?",
        "What's a small gesture I do that makes you feel loved?",
        "What's your favorite memory of us so far?",
        "What does home mean to you now that we're together?",
        "What's something you've learned about love from being with me?",
        "What's a quality of mine you didn't expect to fall for?",
        "What's your favorite way to spend a quiet evening with me?",
        "What's something you're grateful for about our relationship right now?",
        "What's a dream you have for our future together?",
        "What's something about me that made you feel safe early on?",
        "What's a moment you knew you wanted to keep me around?",
        "What's your favorite thing we've built together?",
        "What's something small I do that means more than I probably realize?",
        "What's a tradition you'd love for us to keep forever?",
        "What's the most us moment you can think of?",
        "What's something you hope never changes between us?",
        "What's a way I've helped you grow as a person?",
      ],
      medium: [
        "What's something you need from me during hard times that you don't always ask for?",
        "What's a fear about love you've carried from before us?",
        "What's something you've forgiven me for that we don't talk about much?",
        "What's a way I could love you better?",
        "What's something about your past that shaped how you love now?",
        "What's a wall you've had to work to bring down with me?",
        "What's something you wish I asked you more often?",
        "What's a moment you felt truly seen by me?",
        "What's something you're still figuring out about yourself in this relationship?",
        "What's a hard truth about us you've been sitting on?",
        "What's something you need to hear from me more often?",
        "What's a way you've changed since falling in love with me?",
        "What's something you're proud of us for working through?",
        "What's a moment of vulnerability with me that stuck with you?",
        "What's something you're scared to lose as we grow older together?",
        "What's a way I've surprised you by being different from who you expected?",
        "What's something about commitment that used to scare you?",
      ],
      high: [
        "What's the moment you felt the most desired by me?",
        "What's a fantasy about our future together, physically or emotionally, that excites you?",
        "What's something you find irresistibly attractive about who I am, not just how I look?",
        "What's a way you'd want me to pursue you more?",
        "What's the most vulnerable you've ever felt being close to me?",
        "What's something you've never said out loud about how much you want me?",
        "What's a moment our connection felt the most intense?",
        "What's something you crave more of from our physical connection?",
        "What's a way I make you feel wanted that you'd want more of?",
        "What's the boldest thing you've imagined us doing together?",
        "What's something about intimacy with me you've never put into words?",
        "What's a memory of us that still gives you butterflies?",
        "What's something you find yourself craving when we've been apart?",
        "What's a way you want to be pursued or desired that you've never asked for directly?",
        "What's the most connected you've ever felt to me in a single moment?",
        "What's something about our chemistry that surprised you?",
        "What's a desire you've held back sharing because it felt too bold?",
      ],
    },
  },
};
