import { Intensity, MiniGameId } from "../types";

export const couplesQuestions: Partial<Record<MiniGameId, Record<Intensity, string[]>>> = {
  "would-you-rather": {
    low: [
      "Would you rather cook together every night or order takeout together every night?",
      "Would you rather travel somewhere new together every year or perfect one favorite destination?",
      "Would you rather slow dance in the kitchen or stargaze on a rooftop?",
      "Would you rather get matching pajamas or matching mugs?",
      "Would you rather have a lazy Sunday movie marathon or an adventurous day trip?",
      "Would you rather always get the window seat or always pick the playlist on road trips?",
      "Would you rather redecorate a room together or plan a trip together?",
      "Would you rather adopt a dog or a cat together?",
      "Would you rather have breakfast in bed every weekend or dessert after every dinner?",
      "Would you rather learn a new hobby together or perfect one you already share?",
      "Would you rather send each other good morning texts or good night texts every day?",
      "Would you rather have a home-cooked date night in or a dressed-up date night out?",
      "Would you rather plan surprises for each other or always know what's coming?",
      "Would you rather share a playlist or share a watchlist?",
      "Would you rather take a cooking class together or a dance class together?",
      "Would you rather have a couple's nickname or a couple's handshake?",
      "Would you rather spend a rainy day baking together or reading together?",
      "Would you rather have an inside joke that lasts forever or a song that's forever ours?",
      "Would you rather host game nights or go out for trivia together?",
      "Would you rather have a shared garden or a shared bookshelf?",
      "Would you rather explore a new city together or return to your favorite one every year?",
      "Would you rather wake up early together for sunrise walks or stay up late for stargazing?",
      "Would you rather have a weekly date night ritual or spontaneous surprise dates?",
      "Would you rather learn each other's love language through books or through trial and error?",
      "Would you rather build a blanket fort together or go camping outdoors together?",
      "Would you rather take a road trip with no plans or a fully planned itinerary?",
      "Would you rather have a couple's journal or a shared photo album?",
      "Would you rather try every restaurant in town together or master one cuisine at home?",
      "Would you rather have matching tattoos or matching bracelets?",
      "Would you rather binge a show together every week or read the same book together?",
    ],
    medium: [
      "Would you rather know exactly what I'm thinking, or have me always tell you the truth even when it's hard?",
      "Would you rather I plan every date, or we take turns surprising each other?",
      "Would you rather we argue it out immediately, or take space and talk later?",
      "Would you rather I be brutally honest about your cooking, or always say it's great?",
      "Would you rather relive our first date, or fast-forward to a future memory together?",
      "Would you rather I remember every anniversary perfectly, or surprise you randomly instead?",
      "Would you rather know my biggest fear about us, or my biggest hope for us?",
      "Would you rather we split chores strictly evenly, or trade off based on who minds less?",
      "Would you rather I tell you when you're wrong right away, or pick my battles?",
      "Would you rather do a relationship check-in for fun, or never feel the need to?",
      "Would you rather I show affection more in public, or more in private?",
      "Would you rather know what my friends really think of you, or never ask?",
      "Would you rather we make every big decision together, or trust each other to decide solo sometimes?",
      "Would you rather I apologize first even when I'm not wrong, or we both hold our ground until it's resolved?",
      "Would you rather know my exact love language, or guess it through trial and error forever?",
      "Would you rather we keep separate finances, or merge everything?",
      "Would you rather I tell you a hard truth now, or protect your feelings and wait?",
      "Would you rather know what I actually think of your family, or never ask?",
      "Would you rather we go to couples therapy preventatively, or only if something's really wrong?",
      "Would you rather I text you throughout the day, or save it all up for when we're together?",
      "Would you rather know the real reason behind my longest past relationship ending, or not?",
      "Would you rather I always let you win an argument, or we fight fair every time?",
      "Would you rather have one big blowout fight a year, or small disagreements more often?",
      "Would you rather know exactly how I felt about you before we got together, or keep the mystery?",
      "Would you rather we plan our future in detail, or let it unfold naturally?",
      "Would you rather I tell you if I thought you'd changed, or let you notice on your own?",
      "Would you rather know my honest opinion of your ex, or never hear it?",
      "Would you rather we always celebrate our wins together, or keep some just for ourselves?",
      "Would you rather I ask for help when I'm struggling, or figure it out and tell you after?",
      "Would you rather know if I was ever unsure about us, or never bring it up?",
    ],
    high: [
      "Would you rather I whisper what I love about your body or what I love about your mind — pick one, right now?",
      "Would you rather a slow, romantic night in or a spontaneous, passionate night out?",
      "Would you rather I tell you my biggest fantasy about us, or you guess it first?",
      "Would you rather recreate our first kiss, or our best kiss so far?",
      "Would you rather I describe exactly what attracts me to you physically, or emotionally?",
      "Would you rather a whole night of just kissing, or a whole night of just talking in bed?",
      "Would you rather know what I think about right before I fall asleep next to you, or right when I wake up?",
      "Would you rather I plan a surprise seductive evening, or you plan one for me?",
      "Would you rather we try something new and a little daring together, or perfect something we already love?",
      "Would you rather I tell you the moment I knew I was attracted to you, or the moment I knew I loved you?",
      "Would you rather a slow dance with wandering hands, or a passionate kiss goodbye at the door?",
      "Would you rather I confess my most honest thought about you right now, out loud?",
      "Would you rather spend the next hour giving compliments, or giving massages?",
      "Would you rather I tell you what I find irresistible about you in the morning, or at night?",
      "Would you rather we skip the small talk tonight and go straight to pillow talk?",
      "Would you rather I show you, or tell you, how much I want you right now?",
      "Would you rather a candlelit bath together, or a blanket fort with wandering hands?",
      "Would you rather I describe my favorite moment of intimacy with you in detail, or you describe yours?",
      "Would you rather we try a new place to be intimate together, or perfect our favorite spot?",
      "Would you rather I tell you exactly what I want tonight, or you take the lead and surprise me?",
      "Would you rather a slow striptease to your favorite song, or a surprise makeout the second I walk in?",
      "Would you rather I whisper the boldest thing on my mind, or write it down for you to find later?",
      "Would you rather we spend the whole evening with no phones, just each other, or plan something adventurous outside?",
      "Would you rather I tell you what I think about when I miss you, or show you when I see you next?",
      "Would you rather a slow, teasing morning together, or a spontaneous afternoon we sneak away for?",
      "Would you rather I describe the exact moment our chemistry became undeniable, or relive it together?",
      "Would you rather we role-play meeting for the first time again, or skip straight to your favorite part of us?",
      "Would you rather I tell you the boldest thing I've thought about doing with you, or act it out?",
      "Would you rather a whole night of compliments and touch with no rushing, or a spontaneous, urgent reunion?",
      "Would you rather I describe what I crave most about our physical connection, or you go first?",
    ],
  },
  "two-truths-a-lie": {
    low: [
      "Share three statements about how you pictured your future partner as a kid — two true, one false.",
      "Share three statements about your first celebrity crush — two true, one false.",
      "Share three statements about your idea of a perfect date — two true, one false.",
      "Share three statements about your favorite memory together — two true, one false.",
      "Share three statements about what you thought of your partner when you first met — two true, one false.",
      "Share three statements about your love language — two true, one false.",
      "Share three statements about a gift you've given or received — two true, one false.",
      "Share three statements about your dream home together — two true, one false.",
      "Share three statements about a trip you'd love to take together — two true, one false.",
      "Share three statements about your favorite lazy day activity together — two true, one false.",
      "Share three statements about your first impression of your partner's family — two true, one false.",
      "Share three statements about a tradition you'd like to start together — two true, one false.",
      "Share three statements about your wedding, past or future — two true, one false.",
      "Share three statements about a compliment you've received from your partner — two true, one false.",
      "Share three statements about your favorite date you've been on together — two true, one false.",
      "Share three statements about something you admire about your partner — two true, one false.",
      "Share three statements about how you'd describe your relationship to a stranger — two true, one false.",
      "Share three statements about your ideal Sunday together — two true, one false.",
      "Share three statements about how your friends describe your relationship — two true, one false.",
      "Share three statements about your favorite inside joke together — two true, one false.",
      "Share three statements about a movie or show that reminds you of your relationship — two true, one false.",
      "Share three statements about the first trip you took together — two true, one false.",
      "Share three statements about a skill you wish you both had — two true, one false.",
      "Share three statements about your partner's family traditions — two true, one false.",
      "Share three statements about how you met each other's friends — two true, one false.",
      "Share three statements about your favorite shared hobby — two true, one false.",
      "Share three statements about a pet name you use for each other — two true, one false.",
      "Share three statements about your partner's morning routine — two true, one false.",
      "Share three statements about the playlist that reminds you of your relationship — two true, one false.",
      "Share three statements about a cozy night in you remember fondly — two true, one false.",
      "Share three statements about your partner's comfort food — two true, one false.",
      "Share three statements about a compliment that stuck with you — two true, one false.",
    ],
    medium: [
      "Share three statements about your past relationships — two true, one false.",
      "Share three statements about a fight you've had and how it ended — two true, one false.",
      "Share three statements about a habit of your partner's you secretly love — two true, one false.",
      "Share three statements about a time you felt jealous — two true, one false.",
      "Share three statements about your biggest insecurity in relationships — two true, one false.",
      "Share three statements about the moment you knew this was serious — two true, one false.",
      "Share three statements about a time your partner surprised you — two true, one false.",
      "Share three statements about something you've never told your partner — two true, one false.",
      "Share three statements about a compromise you've had to make in this relationship — two true, one false.",
      "Share three statements about a time you almost broke up — two true, one false.",
      "Share three statements about your partner's family that surprised you — two true, one false.",
      "Share three statements about how you handle conflict — two true, one false.",
      "Share three statements about a white lie you've told your partner — two true, one false.",
      "Share three statements about your biggest relationship fear — two true, one false.",
      "Share three statements about a time you felt most loved — two true, one false.",
      "Share three statements about an ex that still comes up sometimes — two true, one false.",
      "Share three statements about something you'd change about how you two communicate — two true, one false.",
      "Share three statements about a time you had to compromise on something big — two true, one false.",
      "Share three statements about an insecurity your partner helped you with — two true, one false.",
      "Share three statements about the longest you two have gone without talking after a fight — two true, one false.",
      "Share three statements about something you learned about love from your parents — two true, one false.",
      "Share three statements about a time distance, physical or emotional, tested your relationship — two true, one false.",
      "Share three statements about a boundary you've had to set in this relationship — two true, one false.",
      "Share three statements about a moment you doubted the relationship, even briefly — two true, one false.",
      "Share three statements about how you two handle money differently — two true, one false.",
      "Share three statements about a friend's opinion of your relationship that surprised you — two true, one false.",
      "Share three statements about the most vulnerable you've been with your partner — two true, one false.",
      "Share three statements about a time you had to rebuild trust — two true, one false.",
      "Share three statements about something your partner does that used to bother you but doesn't anymore — two true, one false.",
      "Share three statements about a fear of commitment you've had — two true, one false.",
      "Share three statements about how your relationship has changed you for the better — two true, one false.",
      "Share three statements about a time you felt unheard in this relationship — two true, one false.",
    ],
    high: [
      "Share three statements about your biggest fantasy involving your partner — two true, one false.",
      "Share three statements about the most attracted you've ever been to your partner — two true, one false.",
      "Share three statements about a risky or daring thing you've done together — two true, one false.",
      "Share three statements about your partner's most attractive quality — two true, one false.",
      "Share three statements about the first time you felt real chemistry with your partner — two true, one false.",
      "Share three statements about something you find irresistible about your partner — two true, one false.",
      "Share three statements about a place you'd love to be intimate together that you haven't tried — two true, one false.",
      "Share three statements about your wildest date idea — two true, one false.",
      "Share three statements about a moment you couldn't keep your hands off each other — two true, one false.",
      "Share three statements about something you've always wanted to try together — two true, one false.",
      "Share three statements about your partner's best physical feature, in your opinion — two true, one false.",
      "Share three statements about a daydream you've had about your partner — two true, one false.",
      "Share three statements about the most spontaneous thing you've done together — two true, one false.",
      "Share three statements about a compliment you've been too shy to say out loud — two true, one false.",
      "Share three statements about your idea of a perfect romantic night — two true, one false.",
      "Share three statements about something that instantly makes you attracted to your partner — two true, one false.",
      "Share three statements about a surprise you've kept secret to keep the romance alive — two true, one false.",
      "Share three statements about the last time you initiated something intimate — two true, one false.",
      "Share three statements about your partner's touch that you crave the most — two true, one false.",
      "Share three statements about a fantasy you've thought about but never brought up — two true, one false.",
      "Share three statements about the most spontaneous moment of passion you've shared — two true, one false.",
      "Share three statements about something your partner wears that drives you wild — two true, one false.",
      "Share three statements about a time the chemistry between you two surprised even you — two true, one false.",
      "Share three statements about your partner's voice and the effect it has on you — two true, one false.",
      "Share three statements about a place outside the bedroom you've thought about being intimate — two true, one false.",
      "Share three statements about the boldest message you've ever sent your partner — two true, one false.",
      "Share three statements about a compliment about your body that made you feel most desired — two true, one false.",
      "Share three statements about the slowest, most drawn-out moment of intimacy you remember — two true, one false.",
      "Share three statements about something you'd love your partner to do more often in private — two true, one false.",
      "Share three statements about a time jealousy turned into something passionate between you two — two true, one false.",
      "Share three statements about your partner's scent and how it affects you — two true, one false.",
      "Share three statements about the first time you felt a real spark of desire for your partner — two true, one false.",
      "Share three statements about a daydream you've had about your partner during a boring moment — two true, one false.",
      "Share three statements about something you find yourself thinking about after a good night together — two true, one false.",
      "Share three statements about a role or scenario you'd be curious to play out together — two true, one false.",
      "Share three statements about the way your partner looks at you that makes you weak — two true, one false.",
      "Share three statements about the most confident you've ever felt being intimate with your partner — two true, one false.",
      "Share three statements about a time you two got caught almost being intimate somewhere risky — two true, one false.",
      "Share three statements about something about your chemistry you'd never admit to friends — two true, one false.",
      "Share three statements about your partner's hands and what you think about them — two true, one false.",
      "Share three statements about a slow morning together that turned into something more — two true, one false.",
      "Share three statements about the last time you felt completely consumed by attraction to your partner — two true, one false.",
    ],
  },
  "never-have-i-ever": {
    low: [
      "Never have I ever forgotten our anniversary.",
      "Never have I ever cried during a romantic movie with you.",
      "Never have I ever fallen asleep during date night.",
      "Never have I ever planned a surprise date.",
      "Never have I ever stolen the blanket on purpose.",
      "Never have I ever written you a love note.",
      "Never have I ever taken a cute photo of you without you knowing.",
      "Never have I ever pretended to like a gift from you.",
      "Never have I ever sung to you on purpose.",
      "Never have I ever danced with you in the kitchen.",
      "Never have I ever saved a text from you because it made me smile.",
      "Never have I ever cooked you a meal that didn't go as planned.",
      "Never have I ever cried happy tears because of you.",
      "Never have I ever bragged about you to a stranger.",
      "Never have I ever kept a ticket stub or memento from a date.",
      "Never have I ever planned our whole future out loud in my head.",
      "Never have I ever gotten butterflies just from a text from you.",
      "Never have I ever surprised you with flowers for no reason.",
      "Never have I ever pretended not to be tired just to stay up talking with you.",
      "Never have I ever kept a photo of us as my phone background.",
      "Never have I ever planned an entire date around your favorite things.",
      "Never have I ever laughed so hard with you that I cried.",
      "Never have I ever learned to make your favorite meal just to surprise you.",
      "Never have I ever saved a voicemail from you.",
      "Never have I ever written our names together somewhere silly.",
      "Never have I ever cancelled plans with friends just to spend the evening with you.",
      "Never have I ever gotten nervous introducing you to someone.",
      "Never have I ever teared up watching you sleep because I felt so lucky.",
      "Never have I ever kept a playlist just for us.",
      "Never have I ever driven somewhere far just to see you for an hour.",
      "Never have I ever practiced what I'd say before telling you I love you.",
      "Never have I ever picked out a gift for you months in advance.",
    ],
    medium: [
      "Never have I ever gone through your phone.",
      "Never have I ever been jealous of one of your friends.",
      "Never have I ever exaggerated a story to look better in front of you.",
      "Never have I ever pretended to be asleep to avoid a conversation.",
      "Never have I ever compared our relationship to someone else's.",
      "Never have I ever gotten annoyed and not said why.",
      "Never have I ever kept score of who did more chores.",
      "Never have I ever vented about you to a friend when I was upset.",
      "Never have I ever Googled an ex of yours.",
      "Never have I ever pretended to be fine when I wasn't.",
      "Never have I ever felt insecure about something you said.",
      "Never have I ever gone to bed angry instead of talking it out.",
      "Never have I ever exaggerated how bad my day was for sympathy.",
      "Never have I ever checked your location without telling you.",
      "Never have I ever brought up an old argument during a new one.",
      "Never have I ever been embarrassed by something you did in public.",
      "Never have I ever wondered what our life would look like with someone else.",
      "Never have I ever felt like the less \"into it\" one in an argument.",
      "Never have I ever compared how my friends' relationships look to ours.",
      "Never have I ever needed space after a fight longer than you expected.",
      "Never have I ever assumed the worst about a text you sent.",
      "Never have I ever felt like we were speaking two different love languages.",
      "Never have I ever avoided a topic because I knew it would start a fight.",
      "Never have I ever felt insecure comparing myself to someone from your past.",
      "Never have I ever needed reassurance that you weren't upset with me.",
      "Never have I ever kept replaying an argument in my head after we made up.",
      "Never have I ever felt like I gave more effort in the relationship than you did, even briefly.",
      "Never have I ever hidden how stressed I was to protect you from worrying.",
      "Never have I ever felt jealous of how much time you spend on something that isn't me.",
      "Never have I ever needed you to apologize again even after you already did, just to feel better.",
      "Never have I ever wondered if we were growing in different directions.",
      "Never have I ever felt like a fight was really about something else entirely.",
    ],
    high: [
      "Never have I ever fantasized about you during the day.",
      "Never have I ever tried to seduce you and failed.",
      "Never have I ever gotten jealous seeing someone flirt with you.",
      "Never have I ever sent you a flirty text just to get a reaction.",
      "Never have I ever thought about our first kiss more than once in a day.",
      "Never have I ever wanted to skip an event just to stay in with you.",
      "Never have I ever gotten distracted mid-conversation because of how you looked.",
      "Never have I ever planned a whole evening just to set the mood.",
      "Never have I ever felt nervous before being intimate with you, even now.",
      "Never have I ever thought about a place I'd want to kiss you that we haven't tried.",
      "Never have I ever gotten competitive trying to make you laugh in bed.",
      "Never have I ever replayed a moment with you because it was that good.",
      "Never have I ever gotten shy telling you what I want.",
      "Never have I ever tried a new move just to see your reaction.",
      "Never have I ever wanted to leave a party early just to be alone with you.",
      "Never have I ever complimented you just to see you blush.",
      "Never have I ever thought you looked irresistible in something completely ordinary.",
      "Never have I ever initiated something intimate just because I couldn't stop thinking about you.",
      "Never have I ever gotten distracted at work daydreaming about you.",
      "Never have I ever left a piece of clothing out on purpose just to tease you.",
      "Never have I ever wanted to skip dinner plans just to stay in.",
      "Never have I ever sent a photo I was nervous to send.",
      "Never have I ever felt my heart race just from you walking into the room.",
      "Never have I ever thought about a specific moment with you more than once in the same day.",
      "Never have I ever wanted to be somewhere more private the second you walked in.",
      "Never have I ever gotten a little jealous watching you be charming with someone else, in a good way.",
      "Never have I ever whispered something to you just to see your reaction.",
      "Never have I ever thought our chemistry got even better with time.",
      "Never have I ever wanted to try something new together but felt too shy to bring it up.",
      "Never have I ever found a completely ordinary moment with you unexpectedly attractive.",
      "Never have I ever gotten butterflies from a single look across the room.",
      "Never have I ever thought about the way you say my name.",
      "Never have I ever wanted to pull you closer in public but held back.",
      "Never have I ever felt nervous the way I did the very first time, even now.",
      "Never have I ever left something unsaid because it felt too bold to say out loud.",
      "Never have I ever thought a slow dance with you felt like more than just a dance.",
      "Never have I ever wanted to know exactly what you were thinking about me in a quiet moment.",
      "Never have I ever teased you on purpose just to build anticipation.",
      "Never have I ever felt like the space between us in a room was too far.",
      "Never have I ever caught myself staring at you a little too long.",
      "Never have I ever wanted to whisper something in your ear at the worst possible moment.",
      "Never have I ever thought about how it felt the first time we were completely alone together.",
    ],
  },
  "truth-or-dare": {
    low: [
      "Truth: What's the first thing you noticed about me?",
      "Dare: Give your partner a genuine compliment about something non-physical.",
      "Truth: What's your favorite memory of us so far?",
      "Dare: Recreate the way we first said hello.",
      "Truth: What song reminds you of me?",
      "Dare: Do your best impression of your partner for thirty seconds.",
      "Truth: What's one thing you'd love for us to do together this year?",
      "Dare: Give your partner a two-minute hand massage.",
      "Truth: What's your favorite nickname you've had for me?",
      "Dare: Write a one-line love note and read it out loud.",
      "Truth: What made you say yes to our first date?",
      "Dare: Slow dance together for one minute, even without music.",
      "Truth: What's a small thing I do that makes you smile?",
      "Dare: Take a silly selfie together right now.",
      "Truth: What's your favorite way I show I care?",
      "Dare: Whisper something sweet in your partner's ear.",
      "Truth: What's one thing about me you're proud to show off to others?",
      "Truth: What's a small tradition you'd love for us to start?",
      "Dare: Give your partner a compliment using only your hands to describe it.",
      "Truth: What's your favorite way to spend a Sunday with me?",
      "Dare: Recreate our first photo together, right now.",
      "Truth: What's a song you'd dedicate to us?",
      "Dare: Give your partner a genuine \"thank you\" for something they don't get thanked for enough.",
      "Truth: What's your favorite thing to do together when it's raining?",
      "Dare: Draw a quick doodle of your partner and show them.",
      "Truth: What's the silliest nickname you've ever thought of calling me?",
      "Dare: Tell your partner your favorite memory of meeting their family or friends.",
      "Truth: What's a place you'd love for us to visit together someday?",
      "Dare: Give your partner a high five, a hug, and a compliment — in that order.",
      "Truth: What's something you look forward to about growing old together?",
      "Dare: Text your partner a compliment right now, even if they're next to you.",
      "Truth: What's the most \"us\" thing about your relationship?",
    ],
    medium: [
      "Truth: What's something small that instantly puts you in a bad mood?",
      "Dare: Tell your partner the truth about the last time you were annoyed with them.",
      "Truth: What's a compromise you've made that you're still not totally okay with?",
      "Dare: Text a compliment to your partner right now, even though they're next to you.",
      "Truth: What's something you wish I understood better about you?",
      "Dare: Give your partner a genuine apology for something small, even if it's already resolved.",
      "Truth: What's the pettiest thing you've ever been mad at me for?",
      "Dare: Let your partner ask you anything for the next minute, no dodging.",
      "Truth: When was the last time you felt unappreciated?",
      "Dare: Admit one thing you've been avoiding telling your partner.",
      "Truth: What's a habit of mine you've learned to live with?",
      "Dare: Tell your partner your honest first impression of them.",
      "Truth: What's something you're insecure about in this relationship?",
      "Dare: Give your partner three genuine compliments in a row, no repeats.",
      "Truth: What's a fear you have about our future?",
      "Dare: Let your partner pick your outfit for tomorrow, no complaints.",
      "Truth: What's something you've changed about yourself since being with me?",
      "Truth: What's something you wish we did more of as a couple?",
      "Dare: Tell your partner one thing you've been putting off saying.",
      "Truth: What's a small annoyance you've never brought up?",
      "Dare: Let your partner ask you three tough questions in a row, honestly.",
      "Truth: What's something you've changed your mind about since being together?",
      "Dare: Apologize for the last thing you know you were petty about.",
      "Truth: What's a compromise you're still working on accepting?",
      "Dare: Tell your partner the last time you felt unappreciated, calmly.",
      "Truth: What's something about conflict you wish you handled differently?",
      "Dare: Give your partner one honest piece of feedback about the relationship.",
      "Truth: What's a boundary you need us to respect more?",
      "Dare: Admit the last white lie you told your partner, no matter how small.",
      "Truth: What's something you need from me that you haven't asked for directly?",
      "Dare: Tell your partner the real reason behind your mood last time you seemed off.",
      "Truth: What's a fear about us you've never said out loud?",
    ],
    high: [
      "Truth: What's the most attracted to me you've ever been?",
      "Dare: Kiss your partner somewhere you don't usually.",
      "Truth: What's a fantasy you've never told me about?",
      "Dare: Whisper the first flirty thought that comes to mind.",
      "Truth: What's the boldest thing you've thought about doing with me?",
      "Dare: Give your partner a slow, lingering hug for thirty seconds.",
      "Truth: What outfit of mine drives you crazy?",
      "Dare: Describe out loud what you find irresistible about your partner right now.",
      "Truth: What's something daring you'd want to try together?",
      "Dare: Give your partner a kiss that lasts longer than a normal one.",
      "Truth: When did you last daydream about me during the day?",
      "Dare: Trace your finger along your partner's arm and tell them what you're thinking.",
      "Truth: What's your favorite way to be touched?",
      "Dare: Tell your partner exactly what you want to do the moment this game ends.",
      "Truth: What's the most turned on you've been by something I said?",
      "Dare: Let your partner choose where your next kiss lands.",
      "Truth: What's one thing you've always wanted me to do but never asked for?",
      "Truth: What's the most attracted you've felt to me this week?",
      "Dare: Kiss your partner like it's the first time all over again.",
      "Truth: What's a fantasy you'd want to act out together?",
      "Dare: Whisper the boldest thing on your mind right now.",
      "Truth: What's your favorite thing about our physical chemistry?",
      "Dare: Give your partner a slow kiss on the neck.",
      "Truth: What outfit would you want me to wear tonight?",
      "Dare: Describe, in detail, what you find irresistible about your partner right now.",
      "Truth: What's the most daring place you've thought about being intimate together?",
      "Dare: Trace a slow line from your partner's hand to their shoulder and tell them what you're thinking.",
      "Truth: What's a compliment about your body you'd love to hear more often?",
      "Dare: Give your partner a lingering hug and whisper something only they can hear.",
      "Truth: What's the boldest thing you've ever wanted to try together?",
      "Dare: Let your partner choose exactly how the rest of tonight goes.",
      "Truth: What's the most turned on you've ever been by something completely unexpected?",
      "Dare: Tell your partner three things you want to do with them tonight.",
      "Truth: What's a memory of us that still gives you chills?",
      "Dare: Slow dance together for one minute with your foreheads touching.",
      "Truth: What's something you've always wanted me to whisper to you?",
      "Dare: Give your partner one long, slow kiss — no rushing.",
      "Truth: What's the moment our chemistry felt undeniable to you?",
      "Dare: Tell your partner exactly how you want to be touched right now.",
      "Truth: What's a fantasy involving a specific place you've never told me?",
      "Dare: Hold eye contact with your partner for thirty seconds, no laughing, then tell them what you saw.",
      "Truth: What's the boldest version of tonight you can imagine?",
    ],
  },
  "how-well-do-you-know-me": {
    low: [
      "What's my favorite comfort food?",
      "What's my go-to order at our favorite restaurant?",
      "What's my favorite season and why?",
      "What was my favorite subject in school?",
      "What's my dream job, if money didn't matter?",
      "What's my favorite way to relax after a long day?",
      "Who's my celebrity crush?",
      "What's my favorite movie of all time?",
      "What's a hobby I've always wanted to try?",
      "What's my biggest pet peeve?",
      "What's my go-to karaoke song?",
      "What's my favorite holiday?",
      "What was I like as a kid, in one word?",
      "What's my love language?",
      "What's my favorite way to spend a weekend?",
      "What's a place I've always wanted to travel to?",
      "What's my favorite thing about our relationship?",
      "What's my favorite way to be surprised?",
      "What's my go-to comfort show or movie?",
      "What's a childhood memory I've told you more than once?",
      "What's my favorite thing to do on vacation?",
      "What's the first thing I do when I get home?",
      "What's my favorite kind of weather?",
      "What's a food I could never give up?",
      "What's my proudest achievement?",
      "What's my favorite way to start the morning?",
      "What's something I always order at a coffee shop?",
      "What's my dream weekend getaway?",
      "What's a hobby I've picked up recently?",
      "What's my favorite thing about my job or studies?",
      "What's the last thing that made me laugh really hard?",
      "What's my favorite way to celebrate good news?",
    ],
    medium: [
      "What's my biggest fear?",
      "What's something I'm insecure about?",
      "What's a goal I haven't told many people about?",
      "What's my biggest pet peeve about you, specifically?",
      "What's something that stresses me out that I don't always show?",
      "Who's someone I look up to, and why?",
      "What's a fight we had that actually taught you something about me?",
      "What's something I need more of from you emotionally?",
      "What's a habit of mine I'm trying to break?",
      "What do you think is my biggest strength in this relationship?",
      "What's something I regret not doing?",
      "What's a topic I get defensive about?",
      "What do you think I'd change about our relationship if I could?",
      "What's something I've never admitted I'm jealous of?",
      "What's my honest first impression of your closest friend?",
      "What's something I need space for?",
      "What do you think is my love language, and do I show it the way I want to receive it?",
      "What's something I overthink more than I should?",
      "What's a compliment I have a hard time accepting?",
      "What's something I need to hear after a bad day?",
      "What's a subject I'll talk about for way too long if you let me?",
      "What do you think I'd say is my biggest growth area?",
      "What's a way I show love that you didn't recognize at first?",
      "What's something that instantly puts me in a good mood?",
      "What's a worry I carry that I don't talk about much?",
      "What's something I need alone time to recharge from?",
      "What do you think I'd change about how we argue?",
      "What's a compliment about you I say often?",
      "What's something I'm more sensitive about than I let on?",
      "What do you think stresses me out the most day to day?",
      "What's a value I hold that surprised you when you learned it?",
      "What's something I've gotten better at since we've been together?",
    ],
    high: [
      "What's my biggest turn-on?",
      "What's the moment you think I was most attracted to you?",
      "What do you think is my biggest fantasy?",
      "What's something you think I find irresistible about you?",
      "What's my favorite way to be complimented in an intimate moment?",
      "What do you think crosses my mind when I look at you across a room?",
      "What's something bold you think I'd want to try with you?",
      "What do you think is the most attractive thing about you, according to me?",
      "What's a place you think I'd want to be alone with you?",
      "What do you think I find hardest to say out loud in the bedroom?",
      "What's the boldest compliment you think I've been holding back?",
      "What do you think is my favorite memory of us being intimate?",
      "What's something you think I daydream about doing with you?",
      "What outfit do you think drives me the craziest?",
      "What's something you think I've never told you I want?",
      "What do you think I find most attractive about how you show affection?",
      "What's a moment you think changed how attracted I am to you?",
      "What's my favorite thing about the way you kiss me?",
      "What do you think is the moment I'm most attracted to you during the day?",
      "What's a fantasy you think crosses my mind but I haven't shared?",
      "What do you think I find most attractive about your voice?",
      "What's a touch or gesture you think drives me crazy?",
      "What do you think I daydream about when I'm distracted around you?",
      "What's the boldest thing you think I'd say if I had zero filter right now?",
      "What do you think is my favorite part of getting ready for a date with you?",
      "What's a place you think I've imagined being intimate with you?",
      "What do you think I notice first when you walk into a room?",
      "What's something you think I find irresistible about the way you move?",
      "What do you think I'd want you to whisper to me right now?",
      "What's the outfit you think I secretly hope you wear again?",
      "What do you think is the most vulnerable I've felt with you physically?",
      "What's a compliment about your body you think I've been too shy to say enough?",
      "What do you think I remember most about our most passionate night together?",
      "What's something you think I crave when we've been apart too long?",
      "What do you think I'd choose if I could plan one perfect intimate evening?",
      "What's a way you think I want to be pursued that I haven't said out loud?",
      "What do you think is the moment our chemistry first became undeniable to me?",
      "What's something about touch you think I need more of, according to you?",
      "What do you think I think about right before I fall asleep next to you?",
      "What's the boldest compliment you think I've held back giving you?",
      "What do you think I find most magnetic about your energy?",
      "What's a fantasy you think I'd be nervous to admit even to myself?",
    ],
  },
  "intimate-questions": {
    low: [
      "What made you fall for me, even a little?",
      "What's a small gesture I do that makes you feel loved?",
      "What's your favorite memory of us so far?",
      "What does home mean to you now that we're together?",
      "What's something you've learned about love from being with me?",
      "What's a quality of mine you didn't expect to fall for?",
      "What's your favorite way to spend a quiet evening with me?",
      "What's something you're grateful for about our relationship right now?",
      "What's a dream you have for our future together?",
      "What's something about me that made you feel safe early on?",
      "What's a moment you knew you wanted to keep me around?",
      "What's your favorite thing we've built together?",
      "What's something small I do that means more than I probably realize?",
      "What's a tradition you'd love for us to keep forever?",
      "What's the most us moment you can think of?",
      "What's something you hope never changes between us?",
      "What's a way I've helped you grow as a person?",
      "What's a moment early on when you knew this could be something real?",
      "What's something you love about how we communicate?",
      "What's a way you feel most yourself around me?",
      "What's something about our relationship you'd want to tell your younger self?",
      "What's a quiet moment with me you replay in your mind?",
      "What's something you've never had in a relationship until us?",
      "What's a way I make ordinary days feel special?",
      "What's something about loving me that surprised you?",
      "What's a hope you have for who we'll become together?",
      "What's something you'd want people who love us to know about how we met?",
      "What's a way you feel supported by me that you don't say enough?",
      "What's something about togetherness that means more now than it used to?",
      "What's a memory of comfort with me that you hold onto?",
      "What's something you've never had to explain to me because I just understood?",
      "What's a way we've grown closer that felt natural, not forced?",
    ],
    medium: [
      "What's something you need from me during hard times that you don't always ask for?",
      "What's a fear about love you've carried from before us?",
      "What's something you've forgiven me for that we don't talk about much?",
      "What's a way I could love you better?",
      "What's something about your past that shaped how you love now?",
      "What's a wall you've had to work to bring down with me?",
      "What's something you wish I asked you more often?",
      "What's a moment you felt truly seen by me?",
      "What's something you're still figuring out about yourself in this relationship?",
      "What's a hard truth about us you've been sitting on?",
      "What's something you need to hear from me more often?",
      "What's a way you've changed since falling in love with me?",
      "What's something you're proud of us for working through?",
      "What's a moment of vulnerability with me that stuck with you?",
      "What's something you're scared to lose as we grow older together?",
      "What's a way I've surprised you by being different from who you expected?",
      "What's something about commitment that used to scare you?",
      "What's a way you've had to be brave in this relationship?",
      "What's something about being loved that still feels new to you?",
      "What's a fear about the future you're slowly letting go of, because of us?",
      "What's something you needed to unlearn about love before meeting me?",
      "What's a moment you felt us truly become a team?",
      "What's something you're learning about yourself through loving me?",
      "What's a way I've challenged you to grow, even if it was hard?",
      "What's something about vulnerability that's gotten easier with me?",
      "What's a moment you felt fully accepted by me?",
      "What's something about commitment you understand differently now?",
      "What's a way our differences have made us stronger?",
      "What's something you'd want to apologize for that you haven't yet?",
      "What's a hard season we went through that you're grateful for now?",
      "What's something about trust you had to rebuild or strengthen with me?",
      "What's a way you want us to support each other more as life gets busier?",
    ],
    high: [
      "What's the moment you felt the most desired by me?",
      "What's a fantasy about our future together, physically or emotionally, that excites you?",
      "What's something you find irresistibly attractive about who I am, not just how I look?",
      "What's a way you'd want me to pursue you more?",
      "What's the most vulnerable you've ever felt being close to me?",
      "What's something you've never said out loud about how much you want me?",
      "What's a moment our connection felt the most intense?",
      "What's something you crave more of from our physical connection?",
      "What's a way I make you feel wanted that you'd want more of?",
      "What's the boldest thing you've imagined us doing together?",
      "What's something about intimacy with me you've never put into words?",
      "What's a memory of us that still gives you butterflies?",
      "What's something you find yourself craving when we've been apart?",
      "What's a way you want to be pursued or desired that you've never asked for directly?",
      "What's the most connected you've ever felt to me in a single moment?",
      "What's something about our chemistry that surprised you?",
      "What's a desire you've held back sharing because it felt too bold?",
      "What's the moment you felt the deepest connection between desire and love with me?",
      "What's something about being wanted by me that you didn't know you needed?",
      "What's a way you'd want to be seduced that we haven't tried?",
      "What's the most present you've ever felt during an intimate moment with me?",
      "What's something about your own desire that you've only recently understood?",
      "What's a fantasy that feels more emotional than physical for you?",
      "What's the difference between how you feel loved and how you feel desired by me?",
      "What's a way stepping outside your comfort zone with me has deepened our connection?",
      "What's something about slowing down together that you've come to crave?",
      "What's the boldest way you've ever asked for what you wanted from me?",
      "What's a memory of total trust during an intimate moment with me?",
      "What's something about anticipation that turns you on more than the moment itself?",
      "What's a way you want me to make the first move more often?",
      "What's the most vulnerable thing you've ever wanted to say to me in bed?",
      "What's something about eye contact during intimacy that affects you deeply?",
      "What's a way our relationship has taught you to ask for what you want?",
      "What's something you've discovered about your own desires only because of us?",
      "What's the most desired you've ever felt just from how I looked at you?",
      "What's a slow morning or lazy afternoon with me that turned unexpectedly passionate?",
      "What's something about surrender, letting go of control, that you crave with me?",
      "What's a way words during intimacy affect you more than touch?",
      "What's the boldest thing you've ever wanted to whisper to me but didn't?",
      "What's something about our chemistry you think keeps deepening with time, not fading?",
      "What's a way you want to explore trust and vulnerability with me physically?",
      "What's the most patient, unhurried version of intimacy you've imagined with me?",
      "What's something about being desired for who you are, not just how you look, that means the most?",
      "What's a way you'd want to reconnect physically after a stressful week apart?",
      "What's the most honest thing you could say about what you want from me tonight?",
      "What's something about our physical connection that has healed a part of you?",
      "What's a way you hope our intimacy evolves as we grow old together?",
    ],
  },
};
