import { Intensity, MiniGameId } from "../types";

export const friendsQuestions: Partial<Record<MiniGameId, Record<Intensity, string[]>>> = {
  "would-you-rather": {
    low: [
      "Would you rather be able to fly or be invisible?",
      "Would you rather always have to sing instead of speak, or dance everywhere you walk?",
      "Would you rather live in a treehouse or a houseboat?",
      "Would you rather have a pet dragon or a pet unicorn?",
      "Would you rather only eat pizza or only eat tacos for a year?",
      "Would you rather have super speed or super strength?",
      "Would you rather explore space or explore the deep ocean?",
      "Would you rather always have to whisper or always have to shout?",
      "Would you rather live without music or live without movies?",
      "Would you rather have a rewind button or a pause button for your life?",
      "Would you rather be a famous chef or a famous musician?",
      "Would you rather never use social media again or never watch TV again?",
      "Would you rather talk to animals or speak every human language?",
      "Would you rather go camping in the mountains or relax on a beach?",
      "Would you rather always win at board games or always win at video games?",
      "Would you rather have unlimited tacos or unlimited ice cream for life?",
      "Would you rather teleport anywhere or freeze time whenever you want?",
      "Would you rather have the ability to breathe underwater or survive extreme heat?",
      "Would you rather live in a world without color or without sound?",
      "Would you rather have a personal chef or a personal driver for life?",
      "Would you rather always know when someone is lying or always get away with lying yourself?",
      "Would you rather be able to talk to plants or talk to machines?",
      "Would you rather have an unlimited library or an unlimited movie collection?",
      "Would you rather wake up a morning person or stay a night owl forever?",
      "Would you rather have the power to shrink or the power to grow giant?",
      "Would you rather live on a farm or in a big city?",
      "Would you rather never do laundry again or never do dishes again?",
      "Would you rather have the best seat at every concert or courtside at every game?",
      "Would you rather skip traffic forever or never wait in line again?",
      "Would you rather have a photographic memory or the ability to forget anything on command?",
      "Would you rather always have perfect weather or always get a good parking spot?",
      "Would you rather explore an abandoned castle or an uncharted island?",
      "Would you rather have a magic carpet or your own hot air balloon?",
      "Would you rather be fluent in every language or a master of every instrument?",
      "Would you rather have endless energy or need only two hours of sleep a night?",
      "Would you rather live near the mountains or near the ocean?",
      "Would you rather always get the last laugh or always have the best comeback ready?",
    ],
    medium: [
      "Would you rather accidentally send a text about someone to that person, or accidentally call your teacher \"mom\" or \"dad\" in front of the class again?",
      "Would you rather be famous for something embarrassing or never be famous at all?",
      "Would you rather always say what's on your mind or never share an opinion again?",
      "Would you rather find out your best friend talks about you behind your back (nicely) or never know what people say about you?",
      "Would you rather date someone your friends hate but you love, or date someone your friends love but you're just meh about?",
      "Would you rather be stuck in an elevator with your crush or with your worst enemy?",
      "Would you rather have everyone know your search history or your text messages?",
      "Would you rather give an embarrassing toast at a wedding or trip on stage in front of a crowd?",
      "Would you rather lose all your money or lose all your friends?",
      "Would you rather tell everyone the truth about what you think of them, or never speak to anyone again?",
      "Would you rather your parents read your diary or your browser history?",
      "Would you rather be roasted by everyone in this room or have to roast everyone yourself?",
      "Would you rather admit your biggest fear out loud or share your most embarrassing childhood memory?",
      "Would you rather have a group chat exposed to your family or your boss?",
      "Would you rather find out who has a crush on you, or find out who talks trash about you?",
      "Would you rather be forced to tell a secret every hour or never keep a secret again?",
      "Would you rather kiss and tell everything, or never talk about your love life again?",
      "Would you rather find out your partner's ex still has feelings, or find out your ex has moved on completely?",
      "Would you rather your friends plan an intervention for your bad habit, or never say anything and let you figure it out?",
      "Would you rather be told you talk too much, or that you never share enough?",
      "Would you rather have your worst haircut ever printed on a t-shirt everyone here wears, or have your most embarrassing voicemail played out loud?",
      "Would you rather find out a friend unfollowed you, or that they muted you?",
      "Would you rather explain a weird dream you had about someone in this room, or have them explain one about you?",
      "Would you rather admit to a white lie you're still telling, or confess who you've been avoiding?",
      "Would you rather have everyone rank your best and worst qualities to your face, or never get feedback again?",
      "Would you rather be the friend who's always late, or the friend who's always too early?",
      "Would you rather have your DMs screenshotted and sent to the wrong group chat, or your search history synced to a shared family device?",
      "Would you rather admit the pettiest thing that's ever made you jealous, or the pettiest thing you've ever done out of spite?",
      "Would you rather find out your nickname behind your back, or never know it exists?",
      "Would you rather apologize to someone you don't think deserves it, or never receive an apology you're owed?",
      "Would you rather be caught talking to yourself in the mirror, or caught practicing a text before sending it?",
      "Would you rather your group chat name got read out loud to your parents, or your recent Spotify Wrapped got shared with your crush?",
      "Would you rather admit your worst take on a controversial topic, or defend it for five minutes straight?",
      "Would you rather find out someone has a whole folder of memes about you, or find out you're the villain in someone's story?",
      "Would you rather have your camera roll judged by the group, or your recently deleted folder revealed?",
      "Would you rather tell the group the real reason behind your last breakup, or the real reason behind your last big fight with a friend?",
      "Would you rather admit you've stalked someone's LinkedIn out of spite, or admit you've Googled yourself more than once this month?",
    ],
    high: [
      "Would you rather kiss the person to your left or arm wrestle the person to your right for a prize?",
      "Would you rather share your last five DMs with the group, or let someone post on your social media unsupervised for a day?",
      "Would you rather have everyone read your last five texts out loud, or sing your last search out loud?",
      "Would you rather admit who in this room you'd date, or who you'd never date?",
      "Would you rather reveal your worst dating app opener, or confess your worst date story?",
      "Would you rather let the group rate your dating profile live, or let them pick your next bio?",
      "Would you rather tell the group your biggest turn-off, or your biggest ick?",
      "Would you rather share the last lie you told a friend, or the last lie a friend told you that you know of?",
      "Would you rather admit your pettiest reason for ending a friendship, or a relationship?",
      "Would you rather let the group scroll your camera roll for ten seconds, or your recent calls list?",
      "Would you rather confess a crush you've never told anyone about, or reveal who you stalked most on social media this year?",
      "Would you rather do a dare chosen by the group right now, or answer any one question with total honesty?",
      "Would you rather admit the most embarrassing thing you've done for attention, or the pettiest thing you've done out of jealousy?",
      "Would you rather tell everyone your red flag, or let them guess it?",
      "Would you rather reveal the last time you cried and why, or the last time you lied about being fine?",
      "Would you rather let the room ask you anything for the next sixty seconds, or complete a dare of their choice?",
      "Would you rather admit who you'd pick in a kiss-marry-avoid with two people in this room, or sit out this round?",
      "Would you rather have your last ten searches read aloud, or your last ten payment app transactions shown to the group?",
      "Would you rather confess your most-used dating app red flag, or let the group swipe for you live?",
      "Would you rather admit the last time you lied about your relationship status, or admit the last time you exaggerated a hookup story?",
      "Would you rather text your crush something the group writes right now, or call them on speaker?",
      "Would you rather reveal your celebrity hall pass, or reveal who in this room you'd choose if you had one?",
      "Would you rather share the last thing you said about someone that you'd never say to their face, or let that person ask you anything right now?",
      "Would you rather do an impression of everyone's texting style, or let everyone do an impression of yours?",
      "Would you rather admit your longest situationship and why it ended, or your shortest one and why it started?",
      "Would you rather let the group read your last voice memo, or your last drafted-but-unsent text?",
      "Would you rather confess who you'd trade places with for a week, or who you'd never want to be even for a day?",
      "Would you rather reveal your most unhinged 2am thought from this week, or your most unhinged search from this month?",
      "Would you rather admit to a petty revenge plan you actually followed through on, or one you chickened out of?",
      "Would you rather let the group pick your next tattoo, or your next big purchase?",
      "Would you rather confess the real reason you left a group chat, or the real reason you muted someone here?",
      "Would you rather share your most recent overly-hopeful thought about someone, or let the group guess who it's about?",
      "Would you rather admit which friend you'd call first in a crisis, or which one you'd call last?",
      "Would you rather reveal a secret talent that's a little inappropriate, or a secret opinion that's a little controversial?",
      "Would you rather let the group rate your rizz on a scale of one to ten, or demonstrate it live?",
      "Would you rather confess the last time you manifested a text back, or the last time you left someone on read on purpose?",
      "Would you rather admit your most toxic trait in relationships, or let your friends vote on what it is?",
    ],
  },
  "two-truths-a-lie": {
    low: [
      "Share three statements about your childhood pets, hobbies, or favorite foods — two true, one false.",
      "Share three statements about a trip you've taken — two true, one false.",
      "Share three statements about your family — two true, one false.",
      "Share three statements about your first job — two true, one false.",
      "Share three statements about your favorite school subject — two true, one false.",
      "Share three statements about a talent or skill you have — two true, one false.",
      "Share three statements about your bedroom growing up — two true, one false.",
      "Share three statements about your favorite movie or show — two true, one false.",
      "Share three statements about your best childhood friend — two true, one false.",
      "Share three statements about a sport or hobby you tried — two true, one false.",
      "Share three statements about something you collect or used to collect — two true, one false.",
      "Share three statements about your dream vacation — two true, one false.",
      "Share three statements about your favorite holiday tradition — two true, one false.",
      "Share three statements about the weirdest food you've eaten — two true, one false.",
      "Share three statements about your morning routine — two true, one false.",
      "Share three statements about a nickname you've had — two true, one false.",
      "Share three statements about your first concert or live event — two true, one false.",
      "Share three statements about a job interview you've had — two true, one false.",
      "Share three statements about your favorite teacher ever — two true, one false.",
      "Share three statements about a grade or achievement you were proud of — two true, one false.",
      "Share three statements about your first pet — two true, one false.",
      "Share three statements about a road trip you've taken — two true, one false.",
      "Share three statements about your favorite childhood game — two true, one false.",
      "Share three statements about a costume you've worn — two true, one false.",
      "Share three statements about your dream car — two true, one false.",
      "Share three statements about a time you tried a new hobby — two true, one false.",
      "Share three statements about your favorite season and why — two true, one false.",
      "Share three statements about the last book or show you binged — two true, one false.",
      "Share three statements about a family tradition — two true, one false.",
      "Share three statements about your first day at a new school or job — two true, one false.",
      "Share three statements about a talent show or performance you were in — two true, one false.",
      "Share three statements about your favorite meal to cook — two true, one false.",
    ],
    medium: [
      "Share three statements about your dating history — two true, one false.",
      "Share three statements about your worst date ever — two true, one false.",
      "Share three statements about a rule you've broken — two true, one false.",
      "Share three statements about an embarrassing moment in public — two true, one false.",
      "Share three statements about a lie you've told your parents — two true, one false.",
      "Share three statements about your biggest fear — two true, one false.",
      "Share three statements about a time you got in trouble — two true, one false.",
      "Share three statements about your celebrity crush history — two true, one false.",
      "Share three statements about a time you ghosted someone or got ghosted — two true, one false.",
      "Share three statements about your most impulsive purchase — two true, one false.",
      "Share three statements about a secret talent nobody knows about — two true, one false.",
      "Share three statements about your weirdest habit — two true, one false.",
      "Share three statements about a time you pretended to be sick — two true, one false.",
      "Share three statements about your most embarrassing autocorrect or typo — two true, one false.",
      "Share three statements about a crush you had that no one knew about — two true, one false.",
      "Share three statements about the last argument you had with a friend — two true, one false.",
      "Share three statements about something you regret saying — two true, one false.",
      "Share three statements about a time you broke a promise — two true, one false.",
      "Share three statements about the last time you cried and didn't tell anyone — two true, one false.",
      "Share three statements about a competitive streak you have — two true, one false.",
      "Share three statements about a time you were jealous of a friend — two true, one false.",
      "Share three statements about your worst roommate story — two true, one false.",
      "Share three statements about a time you exaggerated to impress someone — two true, one false.",
      "Share three statements about your most embarrassing fashion phase — two true, one false.",
      "Share three statements about a rumor you started or spread — two true, one false.",
      "Share three statements about the last time you were genuinely scared — two true, one false.",
      "Share three statements about a time you pretended to understand something you didn't — two true, one false.",
      "Share three statements about your worst travel experience — two true, one false.",
      "Share three statements about a time you got caught in a small lie — two true, one false.",
      "Share three statements about the most awkward text you've sent — two true, one false.",
      "Share three statements about a time you regretted trusting someone — two true, one false.",
      "Share three statements about your biggest pet peeve in friendships — two true, one false.",
    ],
    high: [
      "Share three statements about your most embarrassing hookup story — two true, one false.",
      "Share three statements about a secret you've kept from your closest friend — two true, one false.",
      "Share three statements about your biggest relationship red flag — two true, one false.",
      "Share three statements about the wildest thing you've done at a party — two true, one false.",
      "Share three statements about someone you regret dating — two true, one false.",
      "Share three statements about a time you were caught doing something you shouldn't have — two true, one false.",
      "Share three statements about your most controversial opinion — two true, one false.",
      "Share three statements about a time you lied to get out of trouble — two true, one false.",
      "Share three statements about your most jealous moment in a relationship or friendship — two true, one false.",
      "Share three statements about a risky thing you've done for love or attention — two true, one false.",
      "Share three statements about the last time you cried in public — two true, one false.",
      "Share three statements about a time you broke someone's trust — two true, one false.",
      "Share three statements about your most embarrassing search history moment — two true, one false.",
      "Share three statements about a rumor that was started about you — two true, one false.",
      "Share three statements about the last person you had a crush on in this friend group — two true, one false.",
      "Share three statements about the riskiest thing you've done on a dare — two true, one false.",
      "Share three statements about a time you snooped through someone's phone — two true, one false.",
      "Share three statements about the last time you flirted to get out of trouble — two true, one false.",
      "Share three statements about your most dramatic breakup story — two true, one false.",
      "Share three statements about a time you were the other person in someone else's drama — two true, one false.",
      "Share three statements about the wildest rumor about you that was actually true — two true, one false.",
      "Share three statements about your most impulsive romantic decision — two true, one false.",
      "Share three statements about a time you got caught sneaking around — two true, one false.",
      "Share three statements about your most petty act of revenge — two true, one false.",
      "Share three statements about a secret you kept for someone else that wasn't yours to keep — two true, one false.",
      "Share three statements about the last time you lied to a friend's face — two true, one false.",
      "Share three statements about your most chaotic night out — two true, one false.",
      "Share three statements about a time you crossed a line and knew it — two true, one false.",
      "Share three statements about your most embarrassing crush confession — two true, one false.",
      "Share three statements about the last time someone caught real feelings and you didn't — two true, one false.",
      "Share three statements about a time you ghosted someone and regretted it — two true, one false.",
      "Share three statements about the boldest thing you've done to get someone's attention — two true, one false.",
    ],
  },
  "never-have-i-ever": {
    low: [
      "Never have I ever gone skydiving.",
      "Never have I ever broken a bone.",
      "Never have I ever fallen asleep in class.",
      "Never have I ever sung karaoke in public.",
      "Never have I ever gotten lost in another city.",
      "Never have I ever pulled an all-nighter.",
      "Never have I ever cried during a movie.",
      "Never have I ever gone a full day without my phone.",
      "Never have I ever eaten something off the floor.",
      "Never have I ever forgotten someone's name right after meeting them.",
      "Never have I ever laughed so hard I cried.",
      "Never have I ever been on TV or in a newspaper.",
      "Never have I ever gone camping.",
      "Never have I ever won a trophy or award.",
      "Never have I ever tried to teach myself a new language and given up.",
      "Never have I ever fallen asleep during a movie in a theater.",
      "Never have I ever talked to myself out loud in public.",
      "Never have I ever been stung by a bee.",
      "Never have I ever gone an entire week without checking social media.",
      "Never have I ever gotten a perfect score on a test.",
      "Never have I ever cheated at a board game.",
      "Never have I ever cried at a commercial.",
      "Never have I ever tried to bake a cake from scratch and failed.",
      "Never have I ever been the last one picked for a team.",
      "Never have I ever gotten a speeding ticket.",
      "Never have I ever fallen off a bike.",
      "Never have I ever forgotten my own phone number.",
      "Never have I ever binge-watched an entire season in one day.",
      "Never have I ever gotten stage fright.",
      "Never have I ever pretended to be someone else on a phone call.",
      "Never have I ever eaten dessert before dinner on purpose.",
      "Never have I ever gone to a concert alone.",
    ],
    medium: [
      "Never have I ever pretended to like a gift I hated.",
      "Never have I ever stalked someone's social media for hours.",
      "Never have I ever lied about my age.",
      "Never have I ever ghosted someone.",
      "Never have I ever texted an ex I shouldn't have.",
      "Never have I ever pretended to be busy to avoid plans.",
      "Never have I ever taken credit for someone else's idea.",
      "Never have I ever cried to get out of trouble.",
      "Never have I ever had a crush on a friend's partner.",
      "Never have I ever lied on a resume or job application.",
      "Never have I ever snooped through a friend's phone.",
      "Never have I ever pretended to know a song I'd never heard.",
      "Never have I ever faked an excuse to leave a date early.",
      "Never have I ever talked about someone right after they left the room.",
      "Never have I ever accidentally liked an old photo while stalking someone's profile.",
      "Never have I ever lied about where I was.",
      "Never have I ever had a secret nickname for someone I didn't like.",
      "Never have I ever pretended to have read a book I hadn't.",
      "Never have I ever spread a rumor, even a small one.",
      "Never have I ever fake laughed at a joke that wasn't funny.",
      "Never have I ever avoided someone at a party on purpose.",
      "Never have I ever taken a sick day when I wasn't actually sick.",
      "Never have I ever eavesdropped on a conversation I wasn't part of.",
      "Never have I ever pretended not to see a text so I could reply later.",
      "Never have I ever exaggerated a story to make it more interesting.",
      "Never have I ever screenshotted a conversation to show someone else.",
      "Never have I ever un-matched someone out of guilt.",
      "Never have I ever accidentally liked someone's old post while scrolling.",
      "Never have I ever pretended to be somewhere I wasn't.",
      "Never have I ever left someone on read on purpose out of pettiness.",
      "Never have I ever made an excuse to avoid a group hangout.",
    ],
    high: [
      "Never have I ever had a crush on someone in this room.",
      "Never have I ever sent a risky text to the wrong person.",
      "Never have I ever kissed someone and regretted it.",
      "Never have I ever lied to a partner about where I was.",
      "Never have I ever had a one-night stand.",
      "Never have I ever been caught checking someone out.",
      "Never have I ever dated two people at the same time.",
      "Never have I ever snuck someone into my room.",
      "Never have I ever been in love with two people at once.",
      "Never have I ever hooked up with someone I met that same day.",
      "Never have I ever lied about my relationship status.",
      "Never have I ever had a secret relationship.",
      "Never have I ever flirted with someone to get something I wanted.",
      "Never have I ever been caught sneaking out.",
      "Never have I ever had feelings for someone's ex.",
      "Never have I ever sent a message I immediately wanted to unsend.",
      "Never have I ever kissed more than one person in the same week.",
      "Never have I ever fallen for someone I knew was bad for me.",
      "Never have I ever kept a relationship secret from my closest friends.",
      "Never have I ever texted someone new while still talking to someone else.",
      "Never have I ever shown up somewhere just because I knew my crush would be there.",
      "Never have I ever pretended to be over someone when I really wasn't.",
      "Never have I ever used a friend as an excuse to avoid a date.",
      "Never have I ever kissed someone to make another person jealous.",
      "Never have I ever stayed friends with an ex to keep the door open.",
      "Never have I ever lied about how many people I've dated.",
      "Never have I ever gotten feelings for someone I was only supposed to be casual with.",
      "Never have I ever double-texted after telling myself I wouldn't.",
      "Never have I ever compared a new partner to an ex out loud.",
      "Never have I ever flirted with someone knowing they were taken.",
      "Never have I ever let a group chat weigh in on whether to text someone back.",
      "Never have I ever kept talking to someone just because the attention felt good.",
    ],
  },
  "most-likely-to": {
    low: [
      "Who is most likely to become famous one day?",
      "Who is most likely to forget their own birthday?",
      "Who is most likely to win a reality TV show?",
      "Who is most likely to become a millionaire?",
      "Who is most likely to survive a zombie apocalypse?",
      "Who is most likely to become a professional athlete?",
      "Who is most likely to move to another country?",
      "Who is most likely to write a book?",
      "Who is most likely to become a chef?",
      "Who is most likely to get lost using GPS?",
      "Who is most likely to adopt ten pets?",
      "Who is most likely to become the group's parent friend?",
      "Who is most likely to fall asleep first at a sleepover?",
      "Who is most likely to become an influencer?",
      "Who is most likely to cry during an animated movie?",
      "Who is most likely to start a business?",
      "Who is most likely to still be friends with everyone here in twenty years?",
      "Who is most likely to become a YouTuber?",
      "Who is most likely to eat the same meal every day for a month?",
      "Who is most likely to win an award for kindness?",
      "Who is most likely to talk their way out of a parking ticket?",
      "Who is most likely to try every roller coaster at a theme park?",
      "Who is most likely to become a teacher?",
      "Who is most likely to organize a surprise party?",
      "Who is most likely to never grow up?",
      "Who is most likely to move to a new city on a whim?",
      "Who is most likely to become a morning workout person?",
      "Who is most likely to remember everyone's birthday?",
      "Who is most likely to laugh at the wrong moment?",
      "Who is most likely to become a stand-up comedian?",
      "Who is most likely to get emotional at a group photo years from now?",
      "Who is most likely to plan the perfect vacation?",
    ],
    medium: [
      "Who is most likely to text an ex at 2am?",
      "Who is most likely to get married first?",
      "Who is most likely to forget a friend's birthday?",
      "Who is most likely to snoop through someone's phone?",
      "Who is most likely to cry over a breakup for months?",
      "Who is most likely to fall in love at first sight?",
      "Who is most likely to ghost someone?",
      "Who is most likely to stalk an ex on social media?",
      "Who is most likely to get in trouble at a party?",
      "Who is most likely to lie about being okay?",
      "Who is most likely to start drama without meaning to?",
      "Who is most likely to date someone the group doesn't approve of?",
      "Who is most likely to get a tattoo they regret?",
      "Who is most likely to fall for a bad joke every time?",
      "Who is most likely to accidentally double text their crush?",
      "Who is most likely to break a rule and not get caught?",
      "Who is most likely to overshare on a first date?",
      "Who is most likely to fall asleep mid-conversation?",
      "Who is most likely to forget they made plans?",
      "Who is most likely to argue just to win, not because they're right?",
      "Who is most likely to overthink a text for an hour?",
      "Who is most likely to cry happy tears at a friend's wedding?",
      "Who is most likely to start an argument in the group chat?",
      "Who is most likely to hold a grudge the longest?",
      "Who is most likely to give the worst advice with total confidence?",
      "Who is most likely to show up uninvited and get away with it?",
      "Who is most likely to fake being sick to skip something?",
      "Who is most likely to talk about their ex way too much?",
      "Who is most likely to be the reason a plan falls apart?",
      "Who is most likely to say \"I'm fine\" when they're clearly not?",
      "Who is most likely to become obsessed with a new hobby for two weeks and quit?",
      "Who is most likely to accidentally start beef with someone?",
    ],
    high: [
      "Who is most likely to have a secret admirer in this room?",
      "Who is most likely to get married and divorced within a year, on a dare?",
      "Who is most likely to flirt their way out of a speeding ticket?",
      "Who is most likely to have the wildest dating app stories?",
      "Who is most likely to have kissed someone in this room?",
      "Who is most likely to have a secret crush right now?",
      "Who is most likely to end up in a messy love triangle?",
      "Who is most likely to send a risky text and regret it instantly?",
      "Who is most likely to hook up with a stranger on vacation?",
      "Who is most likely to fall for their best friend?",
      "Who is most likely to have the most exes in this room?",
      "Who is most likely to be someone's rebound?",
      "Who is most likely to cause a scene at a wedding over an old flame?",
      "Who is most likely to have a secret relationship nobody knows about?",
      "Who is most likely to flirt with everyone at a party?",
      "Who is most likely to fall in love the fastest?",
      "Who is most likely to have a type that always gets them in trouble?",
      "Who is most likely to have a situationship right now?",
      "Who is most likely to fall for someone completely wrong for them?",
      "Who is most likely to be texting someone in this room later tonight?",
      "Who is most likely to have a crush they haven't told anyone about?",
      "Who is most likely to get back with an ex one more time?",
      "Who is most likely to flirt without realizing it?",
      "Who is most likely to have the messiest group chat about their love life?",
      "Who is most likely to catch feelings first?",
      "Who is most likely to have kissed someone this week?",
      "Who is most likely to be someone's \"type\" without trying?",
      "Who is most likely to have a secret account just for one person to see?",
      "Who is most likely to get proposed to first?",
      "Who is most likely to have the wildest \"how we met\" story someday?",
      "Who is most likely to be the one who got away for someone in this room?",
      "Who is most likely to fall in love on a trip abroad?",
    ],
  },
  "rapid-fire": {
    low: [
      "Name 3 breakfast foods before time runs out.",
      "Name 3 movies you could watch on repeat.",
      "Name 3 superheroes as fast as you can.",
      "Name 3 things you'd bring to a deserted island.",
      "Name 3 cartoon characters from your childhood.",
      "Name 3 songs stuck in your head lately.",
      "Name 3 countries you'd love to visit.",
      "Name 3 board games you actually enjoy.",
      "Name 3 smells that instantly make you happy.",
      "Name 3 things that are overrated.",
      "Name 3 snacks you could never give up.",
      "Name 3 apps on your phone you use daily.",
      "Name 3 things you'd buy if money was no object.",
      "Name 3 words that describe you in one breath.",
      "Name 3 places you consider home.",
      "Name 3 skills you wish you had.",
      "Name 3 things that instantly make your day better.",
      "Name 3 things you'd pack for a weekend trip, fast.",
      "Name 3 shows you'd recommend to anyone.",
      "Name 3 things that make you laugh every time.",
      "Name 3 foods you refuse to eat.",
      "Name 3 places you'd love to live someday.",
      "Name 3 sounds you love.",
      "Name 3 things on your bucket list.",
      "Name 3 hobbies you'd try if you had more time.",
      "Name 3 things you always forget.",
      "Name 3 songs perfect for a road trip.",
      "Name 3 things that instantly relax you.",
      "Name 3 games you were good at as a kid.",
      "Name 3 things you'd want in your dream house.",
      "Name 3 people who inspire you.",
      "Name 3 things you're grateful for right now.",
    ],
    medium: [
      "Name 3 red flags in a relationship, fast.",
      "Name 3 things you'd never tell your parents.",
      "Name 3 celebrity crushes, no hesitating.",
      "Name 3 things you'd change about your life right now.",
      "Name 3 people you'd want on your side in an argument.",
      "Name 3 lies people tell on first dates.",
      "Name 3 things that instantly turn you off.",
      "Name 3 guilty pleasures you won't apologize for.",
      "Name 3 things you'd do if no one was watching.",
      "Name 3 traits your ideal partner needs.",
      "Name 3 things you're insecure about, quickly.",
      "Name 3 arguments you've had that were actually silly.",
      "Name 3 things you'd say in a toast that's a little too honest.",
      "Name 3 secrets you could tell right now, safe ones only.",
      "Name 3 people you'd want to swap lives with for a day.",
      "Name 3 things you do that annoy your friends.",
      "Name 3 excuses you've used to cancel plans.",
      "Name 3 things you'd never admit to your parents, fast.",
      "Name 3 white lies you've told this month.",
      "Name 3 things that make you insecure, quickly.",
      "Name 3 red flags you ignore because someone's attractive.",
      "Name 3 things you do that you'd judge someone else for.",
      "Name 3 excuses for being late that you've actually used.",
      "Name 3 things you'd change about this friend group.",
      "Name 3 arguments you've won that you probably shouldn't have.",
      "Name 3 things you'd never post but think about posting.",
      "Name 3 people you'd want to switch lives with for a week.",
      "Name 3 things you're weirdly competitive about.",
      "Name 3 habits you have that annoy people you love.",
      "Name 3 things you'd do if you won the lottery tomorrow.",
      "Name 3 secrets this group already knows about you.",
      "Name 3 things you'd tell your younger self.",
    ],
    high: [
      "Name 3 things you find instantly attractive, fast.",
      "Name 3 people in this room you'd trust with a secret.",
      "Name 3 dares you'd actually do right now.",
      "Name 3 things you'd never do, even on a dare.",
      "Name 3 red flags you've ignored in the past.",
      "Name 3 things you'd want to know about everyone's love life.",
      "Name 3 celebrities you'd want to switch lives with for a wild weekend.",
      "Name 3 secrets you'll take to the grave, or almost.",
      "Name 3 things that make you a good, or bad, partner.",
      "Name 3 things you'd do differently in your last relationship.",
      "Name 3 people you'd pick for a kiss-marry-avoid without hesitating.",
      "Name 3 things you'd confess after one drink.",
      "Name 3 things about your dating life you've never told this group.",
      "Name 3 rules you'd break for the right person.",
      "Name 3 things you find irresistible in someone.",
      "Name 3 moments you'd redo if you could.",
      "Name 3 things you'd want a partner to never find out.",
      "Name 3 people you'd text right now if you had the guts.",
      "Name 3 things you find attractive that you'd never admit out loud.",
      "Name 3 exes you'd never speak to again.",
      "Name 3 things you'd do on a no-consequences night out.",
      "Name 3 people in this room you'd trust with your phone unlocked.",
      "Name 3 things you'd confess only after a dare.",
      "Name 3 dating app red flags you've personally been guilty of.",
      "Name 3 things you'd want to know about everyone's search history.",
      "Name 3 people you'd pick to go on a blind date with you.",
      "Name 3 things that are instant deal-breakers for you.",
      "Name 3 secrets you've almost told this group.",
      "Name 3 things you'd do to win someone back.",
      "Name 3 people whose love life is more chaotic than yours.",
      "Name 3 things you'd want a fortune teller to tell you about your love life.",
      "Name 3 moments you'd relive just for the butterflies.",
    ],
  },
  charades: {
    low: [
      "Act out: Brushing your teeth.",
      "Act out: Riding a rollercoaster.",
      "Act out: Building a sandcastle.",
      "Act out: Walking a dog.",
      "Act out: Making a sandwich.",
      "Act out: Playing the guitar.",
      "Act out: Ice skating.",
      "Act out: Flying a kite.",
      "Act out: Taking a selfie.",
      "Act out: Cooking a fancy dinner.",
      "Act out: Doing yoga.",
      "Act out: Fishing.",
      "Act out: Painting a wall.",
      "Act out: Blowing up a balloon.",
      "Act out: Riding a horse.",
      "Act out: Playing basketball.",
      "Act out: Folding laundry.",
      "Act out: Vacuuming the living room.",
      "Act out: Shoveling snow.",
      "Act out: Riding a skateboard.",
      "Act out: Setting up a tent.",
      "Act out: Playing the drums.",
      "Act out: Getting a haircut.",
      "Act out: Washing a car.",
      "Act out: Mowing the lawn.",
      "Act out: Feeding a baby.",
      "Act out: Doing the dishes.",
      "Act out: Surfing.",
      "Act out: Skiing down a mountain.",
      "Act out: Watering plants.",
      "Act out: Assembling furniture.",
      "Act out: Playing chess.",
    ],
    medium: [
      "Act out: Getting caught in a lie.",
      "Act out: A bad first date.",
      "Act out: Winning the lottery.",
      "Act out: Being scared of a spider.",
      "Act out: Sneaking out of the house.",
      "Act out: A breakup phone call.",
      "Act out: Trying not to laugh at a funeral.",
      "Act out: Getting a text from your crush.",
      "Act out: Being stuck in traffic and late.",
      "Act out: An awkward elevator ride.",
      "Act out: A job interview gone wrong.",
      "Act out: Meeting your partner's parents for the first time.",
      "Act out: Losing a game and being a sore loser.",
      "Act out: Being caught snooping.",
      "Act out: A first kiss that goes badly.",
      "Act out: Realizing you texted the wrong person.",
      "Act out: A dramatic soap opera argument.",
      "Act out: Realizing you left the stove on.",
      "Act out: Trying to parallel park badly.",
      "Act out: Getting caught singing in the shower.",
      "Act out: A dramatic exit after losing an argument.",
      "Act out: Pretending to enjoy a bad gift.",
      "Act out: Faking an illness to skip work.",
      "Act out: A referee making a terrible call.",
      "Act out: A toddler having a tantrum.",
      "Act out: Trying to act sober.",
      "Act out: A dramatic phone call with bad news.",
      "Act out: Getting caught taking the last slice of pizza.",
      "Act out: A nervous best man giving a speech.",
      "Act out: An overly dramatic sports injury.",
      "Act out: Someone bombing a job interview.",
      "Act out: A very awkward group photo.",
    ],
    high: [
      "Act out: Flirting badly at a bar.",
      "Act out: A seductive walk across the room.",
      "Act out: A steamy soap opera reunion scene.",
      "Act out: Being caught mid-daydream about your crush.",
      "Act out: A dramatic love confession.",
      "Act out: Slow dancing with an imaginary partner.",
      "Act out: A jealous partner catching their date flirting.",
      "Act out: Sending a risky text and immediately regretting it.",
      "Act out: A first date that turns into a spark.",
      "Act out: Being swept off your feet.",
      "Act out: A dramatic breakup in a movie.",
      "Act out: Winking at someone across the room.",
      "Act out: A romantic proposal gone wrong.",
      "Act out: Getting caught staring at your crush.",
      "Act out: A passionate reunion at an airport.",
      "Act out: Trying to play it cool after a compliment.",
      "Act out: A love triangle confrontation.",
      "Act out: A slow-motion movie run into someone's arms.",
      "Act out: Catching someone's eye across a crowded room.",
      "Act out: An over-the-top marriage proposal.",
      "Act out: Sneaking a kiss at a party.",
      "Act out: A telenovela-style dramatic confrontation.",
      "Act out: Getting butterflies on a first date.",
      "Act out: A dramatic \"it's not you, it's me\" breakup.",
      "Act out: Being caught texting your crush under the table.",
      "Act out: An over-the-top wedding toast gone wrong.",
      "Act out: A slow-motion hair flip to impress someone.",
      "Act out: A jealous ex showing up uninvited.",
      "Act out: A first dance at a wedding.",
      "Act out: Trying to look cool in front of a crush and failing.",
      "Act out: A dramatic love letter being written.",
      "Act out: Getting caught mid-flirt by a friend.",
    ],
  },
};
